---
permalink: upgrade/upgrade-ontap-tools.html 
sidebar: sidebar 
keywords: upgrade 
summary: アップグレードは、HA構成と非HA構成の両方でサポートされます。 
---
= ONTAP tools for VMware vSphereから 10.5 へのアップグレード
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereから 10.5 にアップグレードできます。ただし、 ONTAPツール 10.0、10.1、または 10.2 から 10.5 にアップグレードするには、まず 10.3 または 10.4 にアップグレードしてから 10.5 に進む必要があります。

[NOTE]
====
* ASA r2 システムの場合、追加のストレージ可用性ゾーン (SAZ) を設定する前に、 ONTAP tools for VMware vSphereを 10.5 に、 ONTAP を9.16.1 にアップグレードしてください。
* ONTAP tools for VMware vSphereから 10.5 へのアップグレードが失敗した場合は、ロールバックできません。低い RPO またはスナップショット回復を使用してセットアップを復元します。ONTAP tools for VMware vSphereの場合は、ゼロ RPO を使用してセットアップを復元します。


====
.作業を開始する前に
* すべてのノードがアクティブであることを確認します。
* ONTAPシステム証明書とオンボードされた vCenter 証明書が少なくとも 5 日間有効であることを確認します。証明書の有効期限が早く切れると、アップグレードは失敗します。
* すべてのノードに 100 GB の容量を持つ 5 番目のディスクがあることを確認します。
* ノード構成が以下の表の仕様と一致していることを確認します。


|===
| 展開タイプ | ノードあたりのCPU（コア） | ノードあたりのメモリ（GB） | ノードあたりのディスクスペース（GB） | 合計CPU（コア） | メモリ（GB） | 合計ディスク容量（GB） 


| 非HA小規模 | 9 | 18 | 350 | 9 | 18 | 350 


| 非HAメディア | 13 | 26 | 350 | 13 | 26 | 350 


| HA小規模 | 9 | 18 | 350 | 27 | 54 | 1050 


| HAメディア | 13 | 26 | 350 | 39 | 78 | 1050 


| 大規模なHA構成 | 17 | 34 | 350 | 51 | 一 〇 二 | 1050 
|===
* CPU と RAM のホット プラグインが有効になっていることを確認します。
* 低い RPO バックアップを有効にし、1 つのバックアップが vCenter Client インターフェイスに表示されることを確認します。アップグレード前にバックアップ フォルダーをダウンロードしてください。
* 低い RPO のバックアップが推奨されます。ただし、非 HA 展開では、アップグレード前にONTAPツール仮想マシンの静止スナップショットを取得できます。
+
参照 link:../manage/backup-settings.html["バックアップ設定を編集する"] そして link:../manage/recover-backup.html["ONTAPツールのセットアップを回復する"] バックアップとリカバリの詳細については、こちらをご覧ください。



.手順
. ONTAP tools for VMware vSphereアップグレードISOをコンテンツライブラリにアップロードします。
. プライマリ VM ページで、[*アクション*] > [*設定の編集*] を選択します。プライマリ VM 名を識別するには:
+
.. 任意のノードで診断シェルを有効にする
.. 次のコマンドを実行します。
`grep sourceHost /opt/netapp/meta/ansible_vars.yaml`


. *CD/DVD ドライブ* フィールドの編集設定ウィンドウで、*コンテンツ ライブラリ ISO ファイル* を選択します。
. ISO ファイルを選択し、*CD/DVD ドライブ* フィールドの *接続済み* ボックスをオンにして、*OK* をクリックします。
. vCenter Serverで、ONTAP toolsへのコンソールを開きます。
. maintenance ユーザとしてログインします。
. *2* と入力して *システム構成* メニューを選択します。
. *7* と入力して *アップグレード* オプションを選択します。
. プロンプトが表示されたら、vCenter の資格情報を入力します。これは、 ONTAPツールがホストされている vCenter インスタンスです。
+
2 つの vCenter Server トポロジ（アプライアンスが 1 つの vCenter インスタンスでホストされ、別の vCenter インスタンスを管理する）でONTAPツールを使用している場合は、 ONTAPツールをホストしている vCenter インスタンスに制限付きロールを割り当てることができます。以下にリストされているデータストア権限のみを持つ専用の vCenter ユーザーとロールを作成できます。

+
** Allocate space
** Browse datastore
** 低レベルのファイル操作
** Remove file
** Update virtual machine files
** 仮想マシンのメタデータを更新する
+
ONTAPツールによって管理される vCenter インスタンスの場合、vCenter ユーザー アカウントに管理者権限があることを確認します。

+
アップグレード中に、オンボードされたストレージ バックエンド証明書にサブジェクト別名 (SAN) エントリがない場合、不足している SAN を示すプロンプトが表示されます。  SAN を検証せずに続行することを選択した場合、アップグレードは続行されますが、潜在的なセキュリティ リスクがあるため、これはお勧めしません。



. をアップグレードすると、次の処理が自動的に実行されます。
+
.. ゲートウェイ証明書は 1 年間の有効期間で更新されます。以前の SRA アダプタを削除し、新しい 10.5 アダプタをアップロードすると、SRA 証明書の有効期間は 10 年から 1 年に変わります。
.. リモートプラグインがアップグレードされました
.. ONTAPおよびvCenter Serverの証明書が検証され、 ONTAPツールに追加されます
.. バックアップが有効になっています




.次の手順
ONTAP tools for VMware vSphereにアップグレードした後:

* システムアラートを監視し、ゲートウェイ証明書が 1 年後に期限切れになる前に更新する計画を立てます。
* ONTAPツール 10.4 または 10.3 SRA アダプタを削除し、10.5 SRA アダプタ tar ファイルをアップロードします。
* SRA アダプタ tar をアップロードした後、インストール コマンドを実行します。次に、SRA アダプタを再スキャンして、VMware Site Recovery のストレージ レプリケーション アダプタ ページを更新します。


アップグレード後は、次のことが可能になります。

* マネージャのユーザインターフェイスからサービスを無効にする
* 非HAセットアップからHAセットアップへの移行
* 非 HA の小規模構成を非 HA の中規模構成に、または HA の中規模または大規模構成にスケールアップします。


.関連情報
link:../migrate/migrate-to-latest-ontaptools.html["ONTAP tools for VMware vSphereから 10.5 に移行する"]
