---
permalink: migrate/sra-vasa-migration.html 
sidebar: sidebar 
keywords: migrate 
summary: ストレージデータを移行する際、ストレージバックエンドはREST APIを使用して手動でオンボーディングされます。VASA Providerのデータを移行すると、既存のDerbyデータベースからデータがエクスポートされ、MongoDBデータベースにインポートされます。 
---
= VASA プロバイダーを移行し、SRA を更新する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




== VASAプロバイダーの移行手順

. 既存のONTAP tools for VMware vSphereでDerbyポート1527を有効にするには、rootユーザを有効にし、SSHを使用してCLIにログインします。次に、次のコマンドを実行します。
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. ONTAP tools for VMware vSphereをデプロイします。
. 移行する vCenter Server インスタンスを、 ONTAP tools for VMware vSphereに追加します。参照link:../configure/add-vcenter.html["vCenter Serverインスタンスを追加する"]詳細についてはこちらをご覧ください。
. ONTAP ツール プラグインの vCenter Server API からストレージ バックエンドをローカルにオンボードします。
. SwaggerまたはPostmanから次のAPIを実行して移行します。
+
[listing]
----
curl -X POST `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/{vcguid}/migration-jobs`
----
+
次の URL から Swagger にアクセスできます。 `\https://$FQDN_IP_PORT/` 、 例えば： `\https://10.67.25.33:8443/` 。

+
[]
====
* HTTPメソッドとエンドポイント*

このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

|===


| * HTTP メソッド * | * パス * 


| 投稿（ Post ） | /api/v1 
|===
*処理タイプ*

非同期

*カールの例*

[listing]
----
curl -X POST 'https://<OTV-NG-IP>:8443/virtualization/api/v1/vcenters/<vcguid>/migration-jobs' \
--header 'x-auth: <auth_token>' \
--header 'Content-Type: application/json' \
--data '{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "******"
  },
  "database_password": "******"
}'
----
他のリリース移行のリクエスト本文：

[listing]
----
{
  "otv_ip": "xx.xx.xx.xx",
  "vasa_provider_credentials": {
    "username": "xxxxx",
    "password": "*******"
  }
}
----
* JSON出力例*

システムはジョブ オブジェクトを返します。次のステップで使用するためにジョブ識別子を保存します。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
====
. Swaggerで次のURIを使用してステータスを確認します。
+
[listing]
----
curl `\https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true`
----
+
ジョブが完了したら、ジョブ応答の移行レポートを確認します。

. VMware vSphereストレージプロバイダ用のONTAPツールをvCenter Serverに追加し、 link:../configure/registration-process.html["VASA Providerを登録する"] VMware vSphere 用の ONTAP ツールを使用します。
. link:../manage/enable-services.html["VASA Provider の有効化"]ONTAP tools for VMware vSphereのサービス。
. ONTAP Tools for VMware vSphereストレージプロバイダ9.10 / 9.11 / 9.12 / 9.13 VASA Providerサービスをメンテナンスコンソールから停止します。
+
VASA プロバイダーを削除しないでください。

+
古いVASAプロバイダが停止すると、vCenter ServerはONTAP tools for VMware vSphereにフェイルオーバーします。すべてのデータストアと仮想マシンはONTAP tools for VMware vSphereからアクセス可能になり、サービスが提供されます。

. 移行された NFS および VMFS データストアは、データストア検出ジョブの後にONTAP tools for VMware vSphereに表示されます。この処理には最大 30 分かかる場合があります。概要ページで可視性を確認します。
. SwaggerまたはPostmanで次のAPIを使用してパッチの移行を実行します。
+
[]
====
* HTTPメソッドとエンドポイント*

このREST API呼び出しでは、次のメソッドとエンドポイントを使用します。

|===


| * HTTP メソッド * | * パス * 


| パッチ | /api/v1 
|===
*処理タイプ*

非同期

*カールの例*

[listing]
----
curl  -X PATCH  `\https://xx.xx.xx.xx:8443/virtualization/api/v1/vcenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdbb887d43`
----
* JSON出力例*

ジョブオブジェクトが返されます。次の手順で使用するには、ジョブIDを保存する必要があります。

[listing]
----
{
  "id": 123,
  "migration_id": "d50073ce-35b4-4c51-9d2e-4ce66f802c35",
  "status": "running"
}
----
PATCH処理の要求の本文が空です。


NOTE: UUIDは、移行後のAPIに対する応答で返される移行UUIDです。

パッチ移行APIを実行すると、すべてのVMがストレージポリシーに準拠します。

====


.次の手順
移行を完了し、 ONTAPツール 10.5 を vCenter Server に登録したら、次の手順を実行します。

* *検出* が完了するまで待機します。完了すると、システムはすべてのホスト上の証明書を自動的に更新します。
* データストアおよび仮想マシンの操作を開始する前に待機します。待機時間は、ホスト、データストア、および仮想マシンの数によって異なります。待たないと、時々失敗が発生する可能性があります。


アップグレード後に仮想マシンのコンプライアンス状態が古い場合は、次の手順に従ってストレージポリシーを再適用します。

. データストアに移動し、*概要* > *VM ストレージ ポリシー* を選択します。
+
システムは、*VM ストレージ ポリシー コンプライアンス* のコンプライアンス ステータスを *古い* と表示します。

. ストレージ VM ポリシーと対応する VM を選択します。
. *適用*を選択します。
+
*VM ストレージ ポリシー コンプライアンス* のコンプライアンス ステータスは、準拠として表示されます。



.関連情報
* link:../concepts/rbac-learn-about.html["ONTAP Tools for VMware vSphere 10 RBACの詳細"]
* link:../upgrade/upgrade-ontap-tools.html["ONTAP tools for VMware vSphereから 10.5 へのアップグレード"]




== ストレージレプリケーションアダプタ(SRA)を更新する手順

.作業を開始する前に
リカバリプランにおいて、保護サイトとは仮想マシンが現在実行されている場所を指し、リカバリサイトとは仮想マシンがリカバリされる場所を指します。SRMVMware Live Site Recovery アプライアンス インターフェイスには、保護されたサイトとリカバリ サイトの詳細とともにリカバリ プランの状態が表示されます。リカバリ プランでは、[CLEANUP] ボタンと [REPROTECT] ボタンは無効になっていますが、[TEST] ボタンと [RUN] ボタンは有効なままです。これは、サイトがデータリカバリの準備ができていることを示します。SRAを移行する前に、一方のサイトが保護状態、もう一方のサイトがリカバリ状態であることを確認してください。


NOTE: フェイルオーバーは完了しているが再保護が保留中の場合は、移行を開始しないでください。移行を続行する前に、再保護プロセスが完了していることを確認してください。テスト フェイルオーバーが進行中の場合は、テスト フェイルオーバーをクリーンアップして移行を開始します。

. VMware Site RecoveryでONTAP tools SRAアダプタfor VMware vSphere 9.xxを削除するには、次の手順を実行します。
+
.. VMware Live Site Recovery構成管理ページに移動します。
.. Storage Replication Adapter *セクションに移動します。
.. 省略記号メニューから* Reset configuration *を選択します。
.. 省略記号メニューから*削除*を選択します。


. これらの手順は、保護サイトとリカバリサイトの両方で実行します。
+
.. link:../manage/enable-services.html["ONTAP Tools for VMware vSphereサービスを有効にする"]
.. ONTAP tools for VMware vSphereを以下の手順で設定します。link:../protect/configure-on-srm-appliance.html["VMware Live Site RecoveryアプライアンスでのSRAの設定"] 。
.. VMware Live Site Recovery インターフェースで、*Discover Arrays* と *Discover Devices* を実行します。移行前と同じようにデバイスが表示されることを確認します。



