---
permalink: deploy/ha-three-node-deployment.html 
sidebar: sidebar 
keywords:  
summary: HAは、小規模、中規模、大規模のいずれかの構成で構成できます。 
---
= HA構成を導入する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HA 3ノードは、小規模、中規模、大規模のいずれかの構成で構成できます。HA環境では、Tridentを使用してサービスデータを格納します。

* 小規模なHA 3ノードには、ノードあたり8個のCPUと16GBのRAMが搭載されています。
* 中規模HA 3つのノードには、ノードあたり12個のCPUと24GBのRAMが搭載されています。
* 大規模なHA 3ノードには、ノードあたり16個のCPUと32GBのRAMが搭載されています。


* 始める前に *

このタスクでは、小規模、中規模、または高可用性構成にHA 3ノードを設置する手順を説明します。


NOTE: コンテンツライブラリの作成は、HA 3ノード構成を導入するための必須の手順です。link:../deploy/download-ontap-tools.html["コンテンツライブラリの作成"]手順については、を参照してください。詳細については https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["コンテンツライブラリの作成と使用"]、ブログを参照してください。

OVAがコンテンツライブラリにインポートされていることを確認します。コンテンツライブラリの名前と、OVAアイテムに付けたライブラリアイテムの名前を手元に置いておきます。


NOTE: 導入を進める前に、ONTAPツールのインストール中に、インベントリ上のクラスタのDistributed Resource Scheduler（DRS）を「保守的」に設定してください。これにより、インストール中にVMが移行されなくなります。

* 手順 *

. vSphereサーバにログインします。
. 作成したリソースプール、またはクラスタまたはOVAを導入するホストに移動します。
. 目的の場所を右クリックし、*[Deploy OVF template...]*を選択します。
+

NOTE: 管理対象のVVOLデータストアには、ONTAP Tools for VMware vSphere仮想マシンを導入しないでください。

. OVAファイルを_.ova_fileのURLから選択するか、または_.ova_fileが保存されているフォルダを参照して、*[次へ]*をクリックします。
. コンテンツライブラリからONTAP Tools for VMware vSphereを導入するには、次の手順を実行します。
+
.. コンテンツライブラリに移動し、展開するライブラリアイテムをクリックします。
.. [Actions]*>*[New VM from this template]*をクリックします。


. コンピュータリソースを選択し、* Next *をクリックします。
. テンプレートの詳細を確認し、*[次へ]*をクリックします。
. ライセンス契約を読んで同意し、*[Next]*をクリックします。
. 導入構成を選択し、*[次へ]*をクリックします。
. 構成用のストレージとディスクファイルを選択し、*[次へ]*をクリックします。
. 各ソースネットワークのデスティネーションネットワークを選択し、*[次へ]*をクリックします。
. [テンプレートのカスタマイズ]ウィンドウで、必要なフィールドに入力し、*[次へ]*をクリックします。
+
** SVMスコープを有効にした場合は、管理IPアドレスでのSVMサポートをすでに有効にしておく必要があります。
** ここで提供される情報は、インストールプロセス中に適切なパターンがあるかどうか検証されます。不一致がある場合は、Webコンソールにエラーメッセージが表示され、誤った情報を修正するように求められます。
** ホスト名には、大文字（A ~ Z）、小文字（a ~ z）、数字（0 ~ 9）、または特殊文字ハイフン（-）を使用する必要があります。デュアルスタックを設定する場合は、IPv6アドレスにマッピングされたホスト名を指定します。


. [選択内容の確認]ウィンドウで詳細を確認し、*[終了]*を選択します。
+
導入タスクが作成されると、進行状況がvSphereタスクバーに表示されます。

. タスクが完了したら、VMの電源をオンにします。
+
インストールが開始されます。インストールの進行状況は、VMのWebコンソールで追跡できます。インストールの一環として、ノード構成が検証されます。OVFフォームの[Customize template]の下のさまざまなセクションで入力された内容が検証されます。不一致がある場合は、修正措置を講じるように求めるダイアログが表示されます。

. ダイアログプロンプトで必要な変更を行います。Tabボタンを使用してパネルを移動し、* OK *を選択します。
+
指定した値が再度検証されます。ONTAP tools for VMware vSphereでは、無効な値を3回修正できます。3回試行しても問題を修正できない場合は、製品のインストールが停止し、新しいVMでインストールを試すことを推奨します。



インストールが完了すると、WebコンソールにONTAP tools for VMware vSphereの状態が表示されます。
