---
permalink: deploy/nonha-deployment.html 
sidebar: sidebar 
keywords:  
summary: 非HAシングルノードは、小規模構成または中規模構成で構成できます。 
---
= 非HAシングルノード構成の導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
非HAのシングルノード構成は、小規模または中規模構成に導入できます。

* 小規模な非HA構成には、8個のCPUと16GBのRAMが搭載されています。
* 中規模の非HA構成には、12個のCPUと24GBのRAMが搭載されています。


* 始める前に *

ネットワークルートが存在することを確認します。ストレージデータネットワークにVM管理ネットワークからアクセスできる必要があります。たとえば、ONTAPにログインし、command_network route create -vserver <SVM>-destination 0.0.0.0/0 -gateway <gateway_ip>_を実行します。

* 手順 *

. vSphereサーバにログインします。
. 作成したリソースプール、またはクラスタまたはOVAを導入するホストに移動します。
. 目的の場所を右クリックし、*[Deploy OVF template...]*を選択します。
+

NOTE: 管理対象のVVOLデータストアには、ONTAP Tools for VMware vSphere仮想マシンを導入しないでください。

. OVAファイルを_.ova_fileのURLから選択するか、または_.ova_fileが保存されているフォルダを参照して、*[次へ]*をクリックします。
. コンピュータリソースを選択し、* Next *をクリックします。
. テンプレートの詳細を確認し、*[次へ]*をクリックします。
. ライセンス契約を読んで同意します。
. 導入構成を選択し、*[次へ]*をクリックします。
+
高度な導入オプションでは、ONTAPでボリュームを作成するための動的ストレージプロビジョニングツールとしてTridentを使用し、簡単な導入ではローカルストレージを使用してボリュームを作成します。

. 構成用のストレージとディスクファイルを選択し、*[次へ]*をクリックします。
. 各ソースネットワークのデスティネーションネットワークを選択し、*[次へ]*をクリックします。
. [テンプレートのカスタマイズ]*で必要な詳細を入力し、*[次へ]*をクリックします。
+
** SVMスコープを有効にした場合は、管理IPアドレスでのSVMサポートをすでに有効にしておく必要があります。
** ここで提供される情報は、インストールプロセス中に適切なパターンがあるかどうか検証されます。不一致がある場合は、Webコンソールにエラーメッセージが表示され、誤った情報を修正するように求められます。
** ホスト名には、大文字（A ~ Z）、小文字（a ~ z）、数字（0 ~ 9）、または特殊文字ハイフン（-）を使用する必要があります。デュアルスタックを設定する場合は、IPv6アドレスにマッピングされたホスト名を指定します。


. [選択内容の確認]ウィンドウで詳細を確認し、*[終了]*を選択します。
+
導入タスクが作成されると、進行状況がvSphereタスクバーに表示されます。

. タスクが完了したら、VMの電源をオンにします。
+
インストールが開始されます。インストールの進行状況は、VMのWebコンソールで追跡できます。インストールの一環として、ノード構成が検証されます。OVFフォームの[Customize template]の下のさまざまなセクションで入力された内容が検証されます。不一致がある場合は、修正措置を講じるように求めるダイアログが表示されます。

. ダイアログプロンプトで必要な変更を行います。Tabボタンを使用してパネルを移動し、* OK *を選択します。
+
指定した値が再度検証されます。ONTAP tools for VMware vSphereでは、無効な値を3回修正できます。3回試行しても問題を修正できない場合は、製品のインストールが停止し、新しいVMでインストールを試すことを推奨します。



インストールが完了すると、WebコンソールにONTAP tools for VMware vSphereの状態が表示されます。
