---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools for VMware vSphereアプライアンスは、NFS / VMFSデータストアをサポートするためのコアサービスを備えた小規模なシングルノードとして常に導入されます。 
---
= ONTAP Tools for VMware vSphereの導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools for VMware vSphereアプライアンスは、NFS / VMFSデータストアをサポートするためのコアサービスを備えた小規模なシングルノードとして常に導入されます。

* 始める前に *

VMwareのコンテンツライブラリは、VMテンプレート、vAppテンプレート、およびその他の種類のファイルを格納するコンテナオブジェクトです。コンテンツライブラリを使用した展開では、ネットワーク接続に依存しないシームレスなエクスペリエンスが提供されます。


NOTE: コンテンツライブラリは、クラスタ内のすべてのホストがアクセスできるように、共有データストアに格納します。アプライアンスの設定をHA構成に変更する前に、OVAを格納するコンテンツライブラリを作成する必要があります。アップロードしたコンテンツライブラリテンプレートは、展開後に削除しないでください。


NOTE: HA導入をあとで有効にする場合は、ONTAPツールをホストしている仮想マシンをESXiホストに直接導入しないでください。代わりに、クラスタまたはリソースプールに導入する必要があります。

適切なコンテンツライブラリがない場合は、次の手順に従ってコンテンツライブラリを作成します。

*コンテンツライブラリの作成*小規模なシングルノード展開のみを使用する場合は、コンテンツライブラリを作成する必要はありません。

.  `.zip`バイナリ（_.ova_）とONTAP tools for VMware vSphereの署名済み証明書を含むファイルをからダウンロードします https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support Site"^]。
. 次のコマンドを使用してvSphere Clientにログインします。 `\https://<vcenterip>/<ui>`
. vSphere Clientの横の省略記号を選択し、*[Content library]*を選択します。
. ページの右側にある*[作成]*を選択します。
. ライブラリの名前を指定し、コンテンツライブラリを作成します。
. 作成したコンテンツライブラリに移動します。
. ページの右側の*[Actions]*を選択し、*[Import item]*を選択してOVAファイルをインポートします。



NOTE: 詳細については https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["コンテンツライブラリの作成と使用"]、ブログを参照してください。

OVAがコンテンツライブラリにインポートされていることを確認します。


NOTE: 導入を進める前に、ONTAPツールのインストール中に、インベントリ上のクラスタのDistributed Resource Scheduler（DRS）を「保守的」に設定してください。これにより、インストール中にVMが移行されなくなります。

.手順
.  `.zip`バイナリ（_.ova_）とONTAP tools for VMware vSphereの署名済み証明書を含むファイルをからダウンロードします https://mysupport.netapp.com/site/products/all/details/otv/downloads-tab["NetApp Support Site"^]。OVAをコンテンツライブラリにインポートした場合は、コンテンツライブラリから直接導入できるため、この手順をスキップして次の手順に進むことができます。
. vSphereサーバにログインします。
. 作成したリソースプール、またはクラスタまたはOVAを導入するホストに移動します。
. 目的の場所を右クリックし、*[Deploy OVF template...]*を選択します。
+

NOTE: ONTAP Tools for VMware vSphere仮想マシンは、管理しているVVOLデータストアには絶対に格納しないでください。

. OVAファイルを_.ova_fileのURLから選択するか、または_.ova_fileが保存されているフォルダを参照して*[次へ]*を選択します。
. コンテンツライブラリからONTAP Tools for VMware vSphereを導入するには、次の手順を実行します。
+
.. コンテンツライブラリに移動し、展開するライブラリアイテムを選択します。
.. [Actions]>[New VM from this template]を選択します。*


. [仮想マシンの名前とフォルダの選択]ウィンドウで、仮想マシン名を入力し、仮想マシンの場所を選択します。[この仮想マシンのハードウェアをカスタマイズする]チェックボックスをオンにすると、[完了の準備完了]ウィンドウが表示される前に、[ハードウェアをカスタマイズする]という手順が有効になります。
. コンピュータリソースを選択し、* Next *を選択します。[Automatically power on deployed VM]チェックボックスをオンにすることもできます。
. テンプレートの詳細を確認し、* Next *を選択します。
. ライセンス契約を読んで同意し、* Next *を選択します。
. 構成用のストレージとディスクファイルを選択し、*[Next]*を選択します。
. 各ソースネットワークのデスティネーションネットワークを選択し、*[Next]*を選択します。
. [テンプレートのカスタマイズ]ウィンドウで、必要なフィールドに入力し、*[次へ]*を選択します。
+
** ここで提供される情報は、インストールプロセス中に適切なパターンがあるかどうか検証されます。不一致がある場合は、Webコンソールにエラーメッセージが表示され、誤った情報を修正するように求められます。
** ホスト名には、大文字（A ~ Z）、小文字（a ~ z）、数字（0 ~ 9）、または特殊文字ハイフン（-）を使用する必要があります。デュアルスタックを設定する場合は、IPv6アドレスにマッピングされたホスト名を指定します。
+

NOTE: Pure IPv6はサポートされていません。mixedモードは、IPv6とIPv4の両方のアドレスを持つVLANでサポートされます。



. [ハードウェアのカスタマイズ]ウィンドウで、CPUホットアドとメモリホットプラグを有効にする必要があります。
. [選択内容の確認]ウィンドウで詳細を確認し、*[終了]*を選択します。
+
導入タスクが作成されると、進行状況がvSphereタスクバーに表示されます。

. タスクが完了したら、VMの電源をオンにします。
+

NOTE: 電源をオンにする前に、VMでCPUとメモリの両方に対してホットプラグインが有効になっていることを確認してください。



インストールの進行状況は、VMのWebコンソールで追跡できます。

OVFフォームに入力した値に不一致がある場合は、修正措置を講じるように求めるダイアログボックスが表示されます。ダイアログボックス内で必要な変更を行い、タブボタンを使用してナビゲートして「OK」を選択します。問題の修正は3回試行できます。3回試行しても問題が解決しない場合は、インストールプロセスが中止されるため、新しいVMでインストールを再試行することを推奨します。
