---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: ONTAP Tools for VMware vSphereアプライアンスは、NFSデータストアとVMFSデータストアをサポートするためのコアサービスを備えた小規模なシングルノードとして導入されます。 
---
= ONTAP Tools for VMware vSphereの導入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Tools for VMware vSphereアプライアンスは、NFSデータストアとVMFSデータストアをサポートするためのコアサービスを備えた小規模なシングルノードとして導入されます。

* 始める前に *

VMwareのコンテンツライブラリは、VMテンプレート、vAppテンプレート、およびその他の種類のファイルを格納するコンテナオブジェクトです。コンテンツライブラリを使用した展開では、ネットワーク接続に依存しないシームレスなエクスペリエンスが提供されます。


NOTE: クラスタ内のすべてのホストがコンテンツライブラリにアクセスできるように、コンテンツライブラリを共有データストアに格納します。アプライアンスをHA構成に設定する前に、OVAを格納するコンテンツライブラリを作成します。展開後にコンテンツライブラリテンプレートを削除しないでください。


NOTE: HA導入をあとで有効にする場合は、ONTAPツールをホストする仮想マシンをESXiホストに直接導入しないでください。代わりにクラスタまたはリソースプールに導入します。

コンテンツライブラリがない場合は、次の手順に従って作成します。

*コンテンツライブラリの作成*小規模なシングルノード展開のみを使用する予定の場合、コンテンツライブラリを作成する必要はありません。

.  `.zip`バイナリ（_.ova_）とONTAP tools for VMware vSphereの署名済み証明書を含むファイルをからダウンロードします https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["NetApp Support Site"^]。
. 次のコマンドを使用してvSphere Clientにログインします。 `\https://<vcenterip>/<ui>`
. vSphere Clientの横の省略記号を選択し、*[Content library]*を選択します。
. ページの右側にある*[作成]*を選択します。
. ライブラリの名前を指定し、コンテンツライブラリを作成します。
. 作成したコンテンツライブラリに移動します。
. ページの右側の*[Actions]*を選択し、*[Import item]*を選択してOVAファイルをインポートします。



NOTE: 詳細については https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["コンテンツライブラリの作成と使用"]、ブログを参照してください。


NOTE: 導入を進める前に、インベントリ上のクラスタのDistributed Resource Scheduler（DRS）を「保守的」に設定してください。これにより、インストール中にVMが移行されなくなります。

.手順
.  `.zip`バイナリ（_.ova_）とONTAP tools for VMware vSphereの署名済み証明書を含むファイルをからダウンロードします https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["NetApp Support Site"^]。OVAをコンテンツライブラリにインポートした場合は、この手順をスキップして次の手順に進むことができます。
. vSphereサーバにログインします。
. OVAを導入するリソースプール、クラスタ、またはホストに移動します。
. 目的の場所を右クリックし、*[Deploy OVF template...]*を選択します。
+

NOTE: ONTAP Tools for VMware vSphere仮想マシンは、自身が管理するVVOLデータストアには絶対に格納しないでください。

. URLからOVAファイルを選択するか、ファイルの場所を参照して、*[Next]*を選択します。
. コンテンツライブラリからONTAP Tools for VMware vSphereを導入するには、次の手順を実行します。
+
.. コンテンツライブラリに移動し、展開するライブラリアイテムを選択します。
.. [Actions]>[New VM from this template]を選択します。*


. [名前とフォルダの選択]フィールドに仮想マシン名を入力し、その場所を選択します。[この仮想マシンのハードウェアをカスタマイズする]チェックボックスをオンにすると、[完了の準備完了]ウィンドウが表示される前に、[ハードウェアをカスタマイズする]という追加の手順が有効になります。
. コンピュータリソースを選択し、* Next *を選択します。必要に応じて、[Automatically power on deployed VM]チェックボックスをオンにします。
. テンプレートの詳細を確認し、* Next *を選択します。
. ライセンス契約を読んで同意し、* Next *を選択します。
. 構成用のストレージとディスクファイルを選択し、*[Next]*を選択します。
. 各ソースネットワークのデスティネーションネットワークを選択し、*[Next]*を選択します。
. [テンプレートのカスタマイズ]ウィンドウで、必要なフィールドに入力し、*[次へ]*を選択します。
+
** この情報はインストール時に検証されます。不一致がある場合は、Webコンソールにエラーメッセージが表示され、修正するように求められます。
** ホスト名には、アルファベット（A ~ Z、a ~ z）、数字（0 ~ 9）、およびハイフン（-）を使用する必要があります。デュアルスタックを設定するには、IPv6アドレスにマッピングされたホスト名を指定します。
+

NOTE: Pure IPv6はサポートされていません。mixedモードは、IPv6アドレスとIPv4アドレスの両方を含むVLANでサポートされます。



. [選択内容の確認]ウィンドウで詳細を確認し、*[終了]*を選択します。
+
導入タスクが作成されると、進行状況がvSphereタスクバーに表示されます。

. [ハードウェアのカスタマイズ]ウィンドウで、CPUホットアドとメモリホットプラグインを有効にします。
. タスクが完了したら、VMの電源をオンにします。


インストールの進行状況は、VMのWebコンソールで追跡できます。

OVFフォームに不一致がある場合は、ダイアログボックスが修正アクションを促します。タブボタンを使用して移動し、必要な変更を行い、「OK」を選択します。問題の解決は3回試行できます。3回試行しても問題が解決しない場合は、インストールプロセスが停止します。新しい仮想マシンでインストールを再試行することを推奨します。
