---
permalink: deploy/prerequisites.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: VMware vSphere 用の ONTAP ツールを導入する前に、導入パッケージのスペース要件といくつかの基本的なホスト システム要件を理解しておく必要があります。 
---
= VMware vSphere の要件と構成の制限に対する ONTAP ツール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツールを導入する前に、導入パッケージのスペース要件といくつかの基本的なホスト システム要件を理解しておく必要があります。

ONTAP Tools for VMware vSphereは、VMware vCenter Server Virtual Appliance（vCSA）で使用できます。ONTAP Tools for VMware vSphereは、ESXiシステムを含むサポートされているvSphere Clientに導入する必要があります。



== システム要件

* *ノードあたりのインストールパッケージのスペース要件*
+
** シンプロビジョニング環境の場合は15GB
** シックプロビジョニングの場合は348GB


* *ホスト システムのサイズ要件* 以下の表は、各展開サイズに推奨されるメモリを示しています。高可用性 (HA) 展開の場合、記載されているアプライアンス サイズの 3 倍が必要です。


|===


| *展開の種類* | *ノードあたりのCPU数* | *ノードあたりのメモリ（GB）* | *ノードあたりシックプロビジョニングされたディスクスペース（GB）* 


| 小規模 | 9 | 18 | 350 


| 中 | 13 | 26 | 350 


| 大規模なメモ：大規模な導入はHA構成専用です。 | 17 | 34 | 350 
|===

NOTE: バックアップを有効にすると、VMが導入されているデータストアに、各ONTAP toolsクラスタにさらに50GBのスペースが必要になります。したがって、非HAには400GBが必要で、HAには合計1100GBのスペースが必要です。



== ストレージとアプリケーションの最小要件

|===
| ストレージ、ホスト、およびアプリケーション | バージョン要件 


| ONTAP | 9.15.1、9.16.0、9.16.1、9.17.0、および 9.17.1 


| ONTAP ToolsでサポートされるESXiホスト | 7.0.3以降 


| サポートされるvCenter ServerのONTAPツール | 7.0U3以降 


| VASA Provider | 3.0 


| OVAアプリケーション | 10.5 


| ONTAP tools仮想マシンを導入するためのESXiホスト | 7.0U3と8.0U3 


| ONTAP tools仮想マシンを導入するためのvCenter Server | 7.0および8.0 
|===

NOTE: ONTAP tools for VMware vSphere 10.4以降では、仮想マシンハードウェアがバージョン10から17に変更されています。

サポートされるONTAP、vCenter Server、ESXiホスト、およびプラグインアプリケーションのバージョンの最新情報については、Interoperability Matrix Tool（IMT）を参照してください。

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Interoperability Matrix Tool で確認してください"^]



== ポートの要件

以下の表は、 NetAppが使用するネットワーク ポートとその用途の概要を示しています。ポートには 3 つの種類があります。

* 外部ポート: これらのポートは、Kubernetes クラスターまたはノードの外部からアクセスできます。これらにより、サービスは外部ネットワークまたはユーザーと通信できるようになり、クラスター環境外のシステムとの統合が可能になります。
* ノード間ポート: これらのポートは、Kubernetes クラスター内のノード間の通信を可能にします。データの共有や共同作業などのクラスター タスクに必要です。単一ノード展開の場合、ノード間ポートはノード内でのみ使用され、外部アクセスは必要ありません。ノード間ポートはクラスター外部からのトラフィックを受け入れることができます。ファイアウォール ルールを使用して、ノード間ポートからのインターネット アクセスをブロックします。
* 内部ポート: これらのポートは、ClusterIP アドレスを使用して Kubernetes クラスター内で通信します。これらは外部に公開されず、ファイアウォール ルールに追加する必要もありません。



NOTE: 中断のない相互通信を維持するために、すべてのONTAPツール ノードが同じサブネット上に存在することを確認します。


|===
| *サービス/コンポーネント名* | * ポート * | *プロトコル* | *ポートタイプ* | * 概要 * 


| ntv-gateway-svc (LB) | 443, 8443 | TCP | 外部 | VASA プロバイダー サービスの着信通信用のパススルー ポート。VASA プロバイダーの自己署名証明書とカスタム CA 証明書はこのポートでホストされます。 


| SSH | 22 | TCP | 外部 | リモート サーバー ログインおよびコマンド実行用のセキュア シェル。 


| rke2 サーバー | 9345 | TCP | ノード間 | RKE2 スーパーバイザー API (信頼できるネットワークに制限)。 


| kube-apiサーバー | 6443 | TCP | ノード間 | Kubernetes API サーバー ポート (信頼できるネットワークに制限)。 


| rpcbind/ポートマッパー | 111 | TCP / UDP | ノード間 | サービス間の RPC 通信に使用されます。 


| coredns (DNS) | 53 | TCP / UDP | ノード間 | クラスター内の名前解決のためのドメイン ネーム システム (DNS) サービス。 


| NTP | 123 | UDP | ノード間 | 時間同期のためのネットワーク タイム プロトコル (NTP)。 


| など | 2379、2380、2381 | TCP | ノード間 | クラスター データのキー値ストア。 


| kube-vip | 2112 | TCP | ノード間 | Kubernetes API サーバー ポート。 


| クベレット | 10248, 10250 | TCP | ノード間 | Kubernetesコンポーネント 


| kubeコントローラー | 10257 | TCP | ノード間 | Kubernetesコンポーネント 


| クラウドコントローラー | 10258 | TCP | ノード間 | Kubernetesコンポーネント 


| kubeスケジューラ | 10259 | TCP | ノード間 | Kubernetesコンポーネント 


| kubeプロキシ | 10249, 10256 | TCP | ノード間 | Kubernetesコンポーネント 


| カリコノード | 9091、9099 | TCP | ノード間 | Calico ネットワーク コンポーネント。 


| コンテナ | 10010 | TCP | ノード間 | コンテナ デーモン サービス。 


| VXLAN（フランネル） | 8472 | UDP | ノード間 | ポッド通信用のオーバーレイ ネットワーク。 
|===

NOTE: HA 展開の場合、すべてのノード間で UDP ポート 8472 が開いていることを確認します。このポートはノード間のポッド間通信を可能にします。これをブロックすると、ノード間ネットワークが中断されます。



== ONTAP tools for VMware vSphereを導入するための構成の制限

次の表は、VMware vSphere用のONTAP toolsを設定する際のガイドとして使用できます。

|===


| * 導入 * | * タイプ * | * VVOLの数* | *ホスト数* 


| HA 認定外 | 小（S） | ~12、000 | 32だ 


| HA 認定外 | 中（M） | 最大24、000 | 64 


| 高可用性 | 小（S） | 最大24、000 | 64 


| 高可用性 | 中（M） | 約50k | 128 


| 高可用性 | 大（L） | ~100k | 256 [注記] 表内のホスト数は、接続されているすべての vCenter の合計数を表します。 
|===


== ONTAP Tools for VMware vSphere - Storage Replication Adapter（SRA）

次の表に、ONTAP tools for VMware vSphereを使用したVMware Live Site Recoveryインスタンスごとにサポートされる数を示します。

|===
| * vCenterの導入規模* | *小さい* | *中* 


| アレイベースのレプリケーションを使用した保護用に構成された仮想マシンの総数 | 2000 | 5000 


| アレイベースのレプリケーション保護グループの総数 | 250 | 250 


| リカバリプランあたりの保護グループの総数 | 50 | 50 


| レプリケートされたデータストア数 | 255 | 255 


| VM数 | 4000 | 7000 
|===
次の表に、VMware Live Site Recoveryの数と、VMware vSphereの導入規模に対応するONTAPツールを示します。

|===


| * VMware Live Site Recoveryインスタンスの数* | * ONTAPツールの導入規模* 


| 最大4 | 小規模 


| 4～8 | 中 


| 8人以上 | 大規模 
|===
詳細については、を参照してください https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/overview/site-recovery-manager-system-requirements/operational-limits-of-site-recovery-manager.html["VMware Live Site Recoveryの運用上の制限"]。
