---
permalink: deploy/sizing-requirements.html 
sidebar: sidebar 
keywords: ONTAP tools,Storage Replication Adapter 
summary: ONTAP tools for VMware vSphereを導入する前に、導入パッケージのスペース要件とホストシステムのいくつかの基本的な要件を理解しておく必要があります。 
---
= ONTAP Tools for VMware vSphereを導入するための前提条件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereを導入する前に、導入パッケージのスペース要件とホストシステムのいくつかの基本的な要件を理解しておく必要があります。

ONTAP Tools for VMware vSphereは、VMware vCenter Server Virtual Appliance（vCSA）で使用できます。ONTAP Tools for VMware vSphereは、ESXiシステムを含むサポートされているvSphere Clientに導入する必要があります。

* *ノードあたりのインストールパッケージのスペース要件*
+
** シンプロビジョニング環境の場合は10GB
** シックプロビジョニングの場合は248GB


* *ノードあたりのホストシステムのサイジング要件*
次の表に、導入サイズおよびノードごとの推奨メモリを示します。


|===


| *展開の種類* | * CPU * | *メモリ（GB）* 


| 小（S） | 8 | 16 


| 中（M） | 12 | 24 


| 大（L） | 16 | 32だ 
|===
link:../deploy/config-limits.html["ONTAP tools for VMware vSphereを導入するための構成の制限"]詳細については、を参照してください。



== ストレージとアプリケーションの最小要件

|===
| ストレージ、ホスト、およびアプリケーション | 最小バージョン要件 


| ONTAP | ONTAP 9.12.1、9.13.1、または9.14.1の最新パッチリリース 


| ESXiホスト | ESXi 7.0.3 


| vCenterサーバ | vCenter 7.0U3 


| VASA Provider | 3.0 


| OVAアプリケーション | 10.1 
|===
サポートされるONTAP、vCenter Server、ESXiホスト、およびプラグインアプリケーションのバージョンの最新情報については、Interoperability Matrix Tool（IMT）を参照してください。

https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["Interoperability Matrix Tool で確認してください"^]
