---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: VMware Live Site Recovery用のStorage Replication Adapter（SRA\）を実行する前に、ストレージシステムをセットアップする必要があります。 
---
= SAN および NAS 環境向けの ONTAP tools で SRA を構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware Live Site Recovery用Storage Replication Adapter（SRA）を実行する前に、ストレージシステムをセットアップする必要があります。



== SAN環境用のSRAの設定

.作業を開始する前に
保護対象サイトとリカバリサイトには、次のプログラムがインストールされている必要があります。

* VMware Live Site Recovery: VMware サイトでは、VMware Live Site Recovery のインストール ドキュメントが提供されています。
+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["VMware Live Site Recoveryについて"]

* SRA: VMware Live Site Recovery にアダプタをインストールします。


.手順
. 保護対象サイトで、プライマリ ESXi ホストがプライマリストレージシステムの LUN に接続されていることを確認します。
. LUNが含まれているigroupにが含まれていることを確認します `ostype` プライマリストレージシステムでオプションを_vmware_に設定します。
. リカバリ サイトの ESXi ホストに、ストレージ仮想マシン (SVM) への適切な iSCSI およびファイバ チャネル接続があることを確認します。セカンダリ サイトの ESXi ホストはセカンダリ サイトのストレージにアクセスできる必要があり、プライマリ サイトの ESXi ホストはプライマリ サイトのストレージにアクセスできる必要があります。
+
そのためには、ESXiホストのSVMでローカルLUNが接続されていることを確認するか、または `iscsi show initiators` SVMでコマンドを実行します。
ESXiホストでマッピングされたLUNへのLUNアクセスをチェックして、iSCSI接続を確認します。





== NAS環境向けのSRAの設定

.作業を開始する前に
保護対象サイトとリカバリサイトには、次のプログラムがインストールされている必要があります。

* VMware Live Site Recovery: VMware Live Site Recovery のインストール ドキュメントは、VMware のサイトにあります - https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["VMware Live Site Recoveryについて"]
* SRA: VMware Live Site Recovery と SRA サーバーにアダプタをインストールします。


.手順
. 保護対象サイトのデータストアに、 vCenter Server に登録された仮想マシンがあることを確認します。
. 保護対象サイトの ESXi ホストに、 Storage Virtual Machine （ SVM ）の NFS エクスポートボリュームがマウントされていることを確認します。
. アレイマネージャウィザードを使用してVMware Live Site Recoveryにアレイを追加する際は、*NFSアドレス*フィールドにNFSエクスポートが存在するIPアドレスやFQDNなどの有効なアドレスが指定されていることを確認してください。*NFSアドレス*フィールドにはNFSホスト名を使用しないでください。
. を使用します `ping` リカバリサイトの各ESXiホストでコマンドを実行し、SVMのNFSエクスポートへの接続に使用されるIPアドレスにホストのVMkernelポートからアクセスできることを確認します。

