---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: Site Recovery Manager（SRM\）用Storage Replication Adapter（SRA\）を実行する前に、ストレージシステムをセットアップする必要があります。 
---
= SAN環境およびNAS環境向けのSRAの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Site Recovery Manager（SRM）向けStorage Replication Adapter（SRA）を実行する前に、ストレージシステムをセットアップする必要があります。



== SAN環境用のSRAの設定

* 必要なもの *

保護対象サイトとリカバリサイトには、次のプログラムがインストールされている必要があります。

* SRM の場合
+
SRM のインストールについては、 VMware サイトのドキュメントを参照してください。

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager のドキュメント"]

* SRA
+
アダプタは SRM にインストールされます。



* 手順 *

. 保護対象サイトで、プライマリ ESXi ホストがプライマリストレージシステムの LUN に接続されていることを確認します。
. LUNが含まれているigroupにが含まれていることを確認します `ostype` プライマリストレージシステムでオプションを_vmware_に設定します。
. リカバリサイトのESXiホストからStorage Virtual Machine（SVM）への適切なiSCSI接続が確立されていることを確認します。セカンダリサイトのESXiホストはセカンダリサイトのストレージにアクセスできる必要があります。同様に、プライマリサイトのESXiホストはプライマリサイトのストレージにアクセスできる必要があります。
+
そのためには、ESXiホストのSVMでローカルLUNが接続されていることを確認するか、または `iscsi show initiators` SVMでコマンドを実行します。
ESXiホストでマッピングされたLUNへのLUNアクセスをチェックして、iSCSI接続を確認します。





== NAS環境用のSRAの設定

* 必要なもの *

保護対象サイトとリカバリサイトには、次のプログラムがインストールされている必要があります。

* SRM の場合
+
SRM のインストールに関するドキュメントは、 VMware のサイトで入手できます。

+
https://www.vmware.com/support/pubs/srm_pubs.html["VMware Site Recovery Manager のドキュメント"]

* SRA
+
SRM と SRA サーバにアダプタをインストールします。



* 手順 *

. 保護対象サイトのデータストアに、 vCenter Server に登録された仮想マシンがあることを確認します。
. 保護対象サイトの ESXi ホストに、 Storage Virtual Machine （ SVM ）の NFS エクスポートボリュームがマウントされていることを確認します。
. Array Manager ウィザードを使用して SRM にアレイを追加するときに、 NFS エクスポートが存在する IP アドレス、ホスト名、 FQDN などの有効なアドレスが *NFS Address* フィールドに指定されていることを確認します。
. を使用します `ping` リカバリサイトの各ESXiホストでコマンドを実行し、SVMのNFSエクスポートへの接続に使用されるIPアドレスにホストのVMkernelポートからアクセスできることを確認します。

