---
permalink: protect/configure-storage-replication-adapter-for-highly-scaled-environment.html 
sidebar: sidebar 
keywords:  
summary: 大規模な環境で最適なパフォーマンスを実現するには、Storage Replication Adapter（SRA\）の推奨設定に従ってストレージのタイムアウト間隔を設定する必要があります。 
---
= 大規模環境向けに ONTAP tools で SRA を構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
大規模な環境で最適なパフォーマンスを実現するには、Storage Replication Adapter（SRA）の推奨設定に従ってストレージのタイムアウト間隔を設定する必要があります。



== ストレージプロバイダの設定

大規模な環境では、VMware Live Site Recoveryで次のタイムアウト値を設定する必要があります。

|===


| * 詳細設定 * | * タイムアウト値 * 


 a| 
`StorageProvider.resignatureTimeout`
 a| 
設定の値を 900 秒から 12000 秒に増やします。



 a| 
`storageProvider.hostRescanDelaySec`
 a| 
60ドルだ



 a| 
`storageProvider.hostRescanRepeatCnt`
 a| 
20



 a| 
`storageProvider.hostRescanTimeoutSec`
 a| 
高い値を設定します（例：99999）。

|===
また、を有効にする必要があります `StorageProvider.autoResignatureMode` オプション

ストレージプロバイダの設定の変更の詳細については、を参照してください https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-provider-settings.html["Change Storage Provider Settings"]。



== ストレージ設定

タイムアウトに達した場合は、 `storage.commandTimeout` および `storage.maxConcurrentCommandCnt` 値を大きくします。


NOTE: このタイムアウト間隔は最大値です。最大タイムアウトに達するまで待つ必要はありません。ほとんどのコマンドは、設定された最大タイムアウト間隔以内に終了します。

SANプロバイダ設定の変更については、を参照してください https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/how-do-i-protect-my-environment/advanced-srm-configuration/reconfigure-srm-settings/change-storage-settings.html["Change Storage Settings"]。
