---
permalink: protect/configure-storage-replication-adapter-for-san-environment.html 
sidebar: sidebar 
keywords:  
summary: VMware Live Site Recovery用のStorage Replication Adapter（SRA\）を実行する前に、ストレージシステムをセットアップする必要があります。 
---
= SAN および NAS 環境向けの ONTAP tools で SRA を構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware Live Site Recovery用Storage Replication Adapter（SRA）を実行する前に、ストレージシステムをセットアップする必要があります。



== SAN環境用のSRAの設定


NOTE: SRAワークフローの整合性グループは、UnifiedとASA r2ストレージシステムの両方で、SANプロトコル（iSCSIとファイバーチャネル）でのみサポートされています。

.作業を開始する前に
保護対象サイトとリカバリサイトには、次のプログラムがインストールされている必要があります。

* VMware Live Site Recovery: VMware サイトでは、VMware Live Site Recovery のインストール ドキュメントが提供されています。
+
https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["VMware Live Site Recoveryについて"]

* SRA: VMware Live Site Recovery にアダプタをインストールします。


iSCSIプロトコル構成については、SRAワークフローを実行する前に以下の点に注意してください：

* *保護されたサイト*：iSCSI ストレージアダプタとデータ LIF の詳細は、データストアをプロビジョニングする際に自動的に構成されます。手動設定は不要です。
* *リカバリサイト*：iSCSIストレージアダプタは、ディザスタリカバリのリソースマッピングに含まれる各ESXiホストで手動で設定する必要があります。各ホストでアダプタを個別に設定しないようにするには、SRAワークフローが設定されているSVMを使用して、リカバリサイトにiSCSIタイプのプレースホルダデータストアを作成します。これにより、iSCSIアダプタと必要なデータLIF IPアドレスがマッピングされたすべてのESXiホストに自動的に追加されます。詳細については、link:../protect/configure-placeholder-datastores.html["ONTAP toolsでプレースホルダデータストアを設定する"]を参照してください。


.手順
. 保護対象サイトで、プライマリ ESXi ホストがプライマリストレージシステムの LUN に接続されていることを確認します。
. プライマリ ストレージ システムで、LUN が `ostype`オプションを_VMware_に設定した igroup に属していることを確認してください。
. リカバリ サイトの ESXi ホストに、ストレージ仮想マシン (SVM) への適切な iSCSI およびファイバ チャネル接続があることを確認します。セカンダリ サイトの ESXi ホストはセカンダリ サイトのストレージにアクセスできる必要があり、プライマリ サイトの ESXi ホストはプライマリ サイトのストレージにアクセスできる必要があります。
+
そのためには、ESXiホストのSVMでローカルLUNが接続されていることを確認するか、または `iscsi show initiators` SVMでコマンドを実行します。
ESXiホストでマッピングされたLUNへのLUNアクセスをチェックして、iSCSI接続を確認します。





== NAS環境向けのSRAの設定


NOTE: SRAワークフローでは、NFSの整合性グループはサポートされていません。NFSデータストアボリュームが整合性グループの下に配置され、保護されている場合、デバイスの検出操作は失敗します。SRAを使用してNFSデータストアを保護する場合、整合性グループを使用しないでください。

.作業を開始する前に
保護対象サイトとリカバリサイトには、次のプログラムがインストールされている必要があります。

* VMware Live Site Recovery: VMware Live Site Recovery のインストール ドキュメントは、VMware のサイトにあります - https://techdocs.broadcom.com/us/en/vmware-cis/live-recovery/live-site-recovery/9-0/about-vmware-live-site-recovery-installation-and-configuration.html["VMware Live Site Recoveryについて"]
* SRA: VMware Live Site Recovery と SRA サーバーにアダプタをインストールします。


.手順
. 保護対象サイトのデータストアに、 vCenter Server に登録された仮想マシンがあることを確認します。
. 保護対象サイトのESXiホストが、Storage Virtual Machine（SVM）からのNFSエクスポートボリュームをマウントしていることを確認してください。
. VMware Live Site Recoveryにアレイを追加するためにArray Managerウィザードを使用する場合、NFSエクスポートが存在する有効なIPアドレスが*NFSアドレス*フィールドに指定されていることを確認してください。*NFSアドレス*フィールドには、NFSホスト名またはFQDNを使用しないでください。
. を使用します `ping` リカバリサイトの各ESXiホストでコマンドを実行し、SVMのNFSエクスポートへの接続に使用されるIPアドレスにホストのVMkernelポートからアクセスできることを確認します。

