---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 保護対象サイトで仮想マシンのグループを保護するには、保護グループを作成する必要があります。 
---
= ONTAP toolsで保護サイトとリカバリサイトを構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護対象サイトで仮想マシンのグループを保護するには、保護グループを作成する必要があります。

新しいデータストアを追加する際は、既存のデータストアグループに含めるか、新しいデータストアを追加して保護用の新しいボリュームまたはコンシステンシグループを作成することができます。保護対象のコンシステンシグループまたはボリュームに新しいデータストアを追加したら、 SnapMirrorを更新し、保護対象サイトとリカバリサイトの両方でストレージ検出を実行します。新しいデータストアを確実に検出・保護するために、検出を手動で実行することも、スケジュールに従って実行することもできます。



== 保護対象サイトとリカバリサイトをペアリング

Storage Replication Adapter（SRA）でストレージシステムを検出できるようにするには、作成された保護対象サイトとリカバリサイトをvSphere Clientを使用してペアリングする必要があります。


NOTE: Storage Replication Adapter（SRA）は、1つの同期関係（Automated Failover Duplexタイプ）と非同期関係SnapMirrorを使用した整合性グループでのファンアウトをサポートします。ただし、整合性グループでの2つの非同期SnapMirror関係を使用したファンアウト、またはボリュームでのファンアウトSnapMirror関係はサポートされていません。VaultタイプのSnapMirror関係は、これらのファンアウト制限の対象外です。SRAでの整合性グループのサポートは、UnifiedおよびASA r2ストレージシステムのSANプロトコル（iSCSIおよびFibre Channel）に限定されています。整合性グループはNFSではサポートされていません。NFSデータストアボリュームが整合性グループに配置されている場合、Discover Devices操作は失敗します。

.作業を開始する前に
* 保護対象サイトとリカバリサイトにVMware Live Site Recoveryがインストールされている必要があります。
* 保護対象サイトとリカバリサイトにSRAをインストールしておく必要があります。


.手順
. vSphere Client のホームページで、*Site Recovery* アイコンをダブルクリックし、*Sites* を選択します。
. [オブジェクト]*>*[アクション]*>*[サイトのペアリング]*を選択します。
. [Site Recovery Managerサーバのペアリング]ダイアログボックスで、保護対象サイトのプラットフォームサービスコントローラのアドレスを入力し、*[次へ]*を選択します。
. Select vCenter Server セクションで、次の手順を実行します。
+
.. 保護対象サイトの vCenter Server が対応するペア候補として表示されていることを確認します。
.. SSO管理クレデンシャルを入力し、*[終了]*を選択します。


. プロンプトが表示されたら、*[はい]*を選択してセキュリティ証明書を受け入れます。


.結果
*オブジェクト* ダイアログ ボックスには、保護されたサイトと回復サイトの両方が表示されます。



== 保護グループを設定します

.作業を開始する前に
ソースとターゲットの両方のサイトで以下を設定する必要があります。

* 同じバージョンのVMware Live Site Recoveryがインストールされている
* 仮想マシン
* 保護対象サイトとリカバリサイトのペアリング
* ソースとデスティネーションのデータストアをそれぞれのサイトにマウントする必要があります


.手順
. vCenter Server にログインし、*Site Recovery* > *Protection Groups* を選択します。
. [保護グループ]*ペインで*[新規]*を選択します。
. 保護グループの名前と説明、方向を指定し、* Next *を選択します。
. *Type*フィールドで、NFSおよびVMFSデータストアの*Type field option...*としてデータストア グループ（アレイ ベースのレプリケーション）を選択します。障害領域は、レプリケーションが有効になっているSVMで構成されます。ピアリングのみが実装されており、問題のないSVMが表示されます。
. Replication groups（レプリケーショングループ）タブで、有効なアレイペアまたは設定した仮想マシンがあるレプリケーショングループのいずれかを選択し、* Next（次へ）*を選択します。
+
レプリケーショングループ上のすべての仮想マシンが保護グループに追加されます。

. 既存のリカバリ プランを選択するか、[新しいリカバリ プランに追加] を選択して新しいリカバリ プランを作成することもできます。
. [Ready to Complete]タブで、作成した保護グループの詳細を確認し、*[Finish]*を選択します。

