---
permalink: protect/configure-array-manager.html 
sidebar: sidebar 
keywords:  
summary: Site Recovery Manager （ SRM ）の Array Manager ウィザードを使用して Storage Replication Adapter \ （ SRA \ ）を設定し、 SRM と Storage Virtual Machine （ SVM \ ）が連携できるようにすることができます。 
---
= アレイマネージャを使用して SRA を設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Site Recovery Manager （ SRM ）の Array Manager ウィザードを使用して Storage Replication Adapter （ SRA ）を設定し、 SRM と Storage Virtual Machine （ SVM ）が連携できるようにすることができます。

* 必要なもの *

* SRMで保護対象サイトとリカバリサイトをペアリングしておく必要があります。
* アレイマネージャを設定する前に、オンボードストレージを設定しておく必要があります。
* 保護対象サイトとリカバリサイト間のSnapMirror関係を設定し、レプリケートしておく必要があります。
* マルチテナンシーを有効にするには、SVM管理LIFを有効にしておく必要があります。


SRA では、クラスタレベルの管理と SVM レベルの管理がサポートされます。クラスタレベルでストレージを追加すると、クラスタ内のすべてのSVMを検出して処理を実行できます。SVM レベルでストレージを追加する場合は、特定の SVM だけを管理できます。

* 手順 *

. SRMで、*[アレイマネージャ]*をクリックし、*[アレイマネージャの追加]*をクリックします。
. 次の情報を入力して、 SRM でアレイを指定します。
+
.. [*Display Name*] フィールドに、アレイマネージャを識別する名前を入力します。
.. 「 * SRA Type * 」フィールドで、「 * ONTAP 向け NetApp Storage Replication Adapter 」を選択します。
.. クラスタまたは SVM への接続情報を入力します。
+
*** クラスタに接続する場合は、クラスタ管理 LIF を入力する必要があります。
*** SVM に直接接続する場合は、 SVM 管理 LIF の IP アドレスを入力する必要があります。
+

NOTE: アレイマネージャを設定するときは、ONTAP toolsでストレージシステムをオンボードしていたのと同じ接続（IPアドレス）をストレージシステムに使用する必要があります。
たとえば、アレイマネージャの設定範囲がSVMである場合は、ONTAP tools for VMware vSphereのストレージをSVMレベルで追加する必要があります。



.. クラスタに接続する場合は、 SVM の名前を * SVM 名 * フィールドに入力します。
+
このフィールドは空白のままにすることもできます。

.. 検出するボリュームを * Volume include list * フィールドに入力します。
+
保護対象サイトではソースボリュームを、リカバリサイトではレプリケートされたデスティネーションボリュームを入力できます。

+
たとえば、ボリュームdst_vol1とSnapMirror関係にあるボリュームsrc_vol1を検出する場合は、保護対象サイトのフィールドでsrc_vol1を指定し、リカバリサイトのフィールドでdst_vol1を指定する必要があります。

.. * （オプション） * Volume exclude list * フィールドに、検出対象から除外するボリュームを入力します。
+
保護対象サイトではソースボリュームを、リカバリサイトではレプリケートされたデスティネーションボリュームを入力できます。

+
たとえば、volume_dst_vol1_とSnapMirror関係にあるvolume_src_vol1_を除外する場合は、保護対象サイトのフィールドで_src_vol1_を指定し、リカバリサイトのフィールドで_dst_vol1_を指定する必要があります。



. 「 * 次へ * 」をクリックします。
. アレイが検出され、[Add Array Manager]ウィンドウの下部に表示されていることを確認し、*[Finish]*をクリックします。


適切な SVM 管理 IP アドレスとクレデンシャルを使用して、リカバリサイトでも同じ手順を実行します。アレイマネージャの追加ウィザードのアレイペアを有効にする画面で、正しいアレイペアが選択されていること、および有効にする準備ができたことを確認する必要があります。
