---
permalink: protect/configure-protection-groups.html 
sidebar: sidebar 
keywords:  
summary: 保護対象サイトで仮想マシンのグループを保護するには、保護グループを作成する必要があります。 
---
= 保護対象サイトとリカバリサイトの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
保護対象サイトで仮想マシンのグループを保護するには、保護グループを作成する必要があります。

新しいデータストアを追加する際は、既存のデータストアグループに含めるか、新しいデータストアを追加して保護用の新しいボリュームまたはコンシステンシグループを作成することができます。保護対象のコンシステンシグループまたはボリュームに新しいデータストアを追加したら、 SnapMirrorを更新し、保護対象サイトとリカバリサイトの両方でストレージ検出を実行します。新しいデータストアを確実に検出・保護するために、検出を手動で実行することも、スケジュールに従って実行することもできます。



== 保護対象サイトとリカバリサイトをペアリング

Storage Replication Adapter（SRA）でストレージシステムを検出できるようにするには、作成された保護対象サイトとリカバリサイトをvSphere Clientを使用してペアリングする必要があります。


NOTE: ストレージ レプリケーション アダプタ (SRA) は、整合性グループ上の自動フェイルオーバー デュプレックス タイプの 1 つの同期関係と非同期関係 SnapMirror によるファンアウトをサポートします。整合性グループで2つの非同期SnapMirrorを使用したただし、ファンアウト、またはボリュームでファンアウトSnapMirrorはサポートされていません。

.作業を開始する前に
* 保護対象サイトとリカバリサイトにVMware Live Site Recoveryがインストールされている必要があります。
* 保護対象サイトとリカバリサイトにSRAをインストールしておく必要があります。


.手順
. vSphere Client のホームページで、*Site Recovery* アイコンをダブルクリックし、*Sites* を選択します。
. [オブジェクト]*>*[アクション]*>*[サイトのペアリング]*を選択します。
. [Site Recovery Managerサーバのペアリング]ダイアログボックスで、保護対象サイトのプラットフォームサービスコントローラのアドレスを入力し、*[次へ]*を選択します。
. Select vCenter Server セクションで、次の手順を実行します。
+
.. 保護対象サイトの vCenter Server が対応するペア候補として表示されていることを確認します。
.. SSO管理クレデンシャルを入力し、*[終了]*を選択します。


. プロンプトが表示されたら、*[はい]*を選択してセキュリティ証明書を受け入れます。


.結果
*オブジェクト* ダイアログ ボックスには、保護されたサイトと回復サイトの両方が表示されます。



== 保護グループを設定します

.作業を開始する前に
ソースとターゲットの両方のサイトで以下を設定する必要があります。

* 同じバージョンのVMware Live Site Recoveryがインストールされている
* 仮想マシン
* 保護対象サイトとリカバリサイトのペアリング
* ソースとデスティネーションのデータストアをそれぞれのサイトにマウントする必要があります


.手順
. vCenter Server にログインし、*Site Recovery* > *Protection Groups* を選択します。
. [保護グループ]*ペインで*[新規]*を選択します。
. 保護グループの名前と説明、方向を指定し、* Next *を選択します。
. *タイプ*フィールドで、*タイプフィールドオプション...*として、NFSおよびVMFSデータストアのデータストアグループ（アレイベースレプリケーション）を選択します。フォールト ドメインは、実際には、レプリケーションが有効になっているSVMです。ピアリングのみが実装されており、問題のないSVMが表示されます。
. Replication groups（レプリケーショングループ）タブで、有効なアレイペアまたは設定した仮想マシンがあるレプリケーショングループのいずれかを選択し、* Next（次へ）*を選択します。
+
レプリケーショングループ上のすべての仮想マシンが保護グループに追加されます。

. 既存のリカバリ プランを選択するか、[新しいリカバリ プランに追加] を選択して新しいリカバリ プランを作成することもできます。
. [Ready to Complete]タブで、作成した保護グループの詳細を確認し、*[Finish]*を選択します。

