---
permalink: protect/map-resource.html 
sidebar: sidebar 
keywords:  
summary: 仮想マシンがどちらか一方のホストグループにフェイルオーバーするように構成されるように、保護対象サイトとリカバリサイトのリソースをマッピングする必要があります。 
---
= リソースマッピングを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
仮想マシンがどちらか一方のホストグループにフェイルオーバーするように構成されるように、保護対象サイトとリカバリサイトのリソースをマッピングする必要があります。

* 必要なもの *

保護対象サイトとリカバリサイトを接続しておく必要があります。


NOTE: Site Recovery Manager （ SRM ）のリソースには、リソースプール、 ESXi ホスト、 vSphere クラスタがあります。

* 手順 *

. vCenter Serverにログインし、* Site Recovery *>* Sites *をクリックします。
. 保護されたサイトを選択し、 * 管理 * をクリックします。
. [ 管理 ] タブで、 [ * リソースマッピング * ] を選択します。
. [新規]*をクリックして、新しいリソースマッピングを作成します。
+
Create Resource Mapping ウィザードが表示されます。

. Create Resource Mapping ウィザードで、次の手順を実行します。
+
.. [ 一致する名前を持つリソースのマッピングを自動的に準備する *] を選択し、 [ 次へ *] をクリックします。
.. 保護サイトとリカバリサイトに必要なデータセンターオブジェクトを選択し、 * マッピングの追加 * をクリックします。
.. マッピングが正常に作成されたら、 * 次へ * をクリックします。
.. 前に使用したオブジェクトを選択してリバースマッピングを作成し、*[完了]*をクリックします。




* 結果 *

リソースマッピングページには、保護対象サイトリソースとリカバリサイトリソースが表示されます。環境内の他のネットワークについても、同じ手順を実行します。
