---
permalink: protect/pair-protected-and-recovery-sites.html 
sidebar: sidebar 
keywords:  
summary: Storage Replication Adapter（SRA\）でストレージシステムを検出できるようにするには、作成された保護対象サイトとリカバリサイトをvSphere Clientを使用してペアリングする必要があります。 
---
= 保護対象サイトとリカバリサイトをペアリング
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Replication Adapter（SRA）でストレージシステムを検出できるようにするには、作成された保護対象サイトとリカバリサイトをvSphere Clientを使用してペアリングする必要があります。


NOTE: Storage Replication Adapter （ SRA ）では、ファンアウト SnapMirror 構成がサポートされません。SnapMirror のファンアウト構成は、ソースボリュームが 2 つの異なるデスティネーションにレプリケートされる構成です。SRMがデスティネーションから仮想マシンをリカバリする必要がある場合、リカバリ中に問題が発生します。

* 必要なもの *

* 保護対象サイトとリカバリサイトにSite Recovery Manager（SRM）をインストールしておく必要があります。
* 保護対象サイトとリカバリサイトにSRAをインストールしておく必要があります。


* 手順 *

. vSphere Clientのホームページで* Site Recovery *をダブルクリックし、* Sites *をクリックします。
. [ * オブジェクト * > * アクション * > * サイトのペアリング * ] をクリックします。
. ペアサイトリカバリマネージャサーバーダイアログボックスで、保護サイトのプラットフォームサービスコントローラのアドレスを入力し、次へ * をクリックします。
. Select vCenter Server セクションで、次の手順を実行します。
+
.. 保護対象サイトの vCenter Server が対応するペア候補として表示されていることを確認します。
.. SSO 管理クレデンシャルを入力し、 [* 終了 * ] をクリックします。


. プロンプトが表示されたら、 [ はい ] をクリックしてセキュリティ証明書を受け入れます。


* 結果 *

保護対象サイトとリカバリサイトの両方が [ オブジェクト ] ダイアログボックスに表示されます。
