---
permalink: protect/update-credentials.html 
sidebar: sidebar 
keywords: SRA credentials, updating 
summary: VMware Live Site RecoveryがSRAと通信するために、クレデンシャルを変更した場合は、VMware Live Site RecoveryサーバのSRAクレデンシャルを更新する必要があります。 
---
= ONTAP toolsでSRA認証情報を更新する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware Live Site RecoveryがSRAと通信するために、クレデンシャルを変更した場合は、VMware Live Site RecoveryサーバのSRAクレデンシャルを更新する必要があります。

.作業を開始する前に
トピックに記載されている手順を実行しておく必要があります link:../protect/configure-on-srm-appliance.html["VMware Live Site RecoveryアプライアンスでのSRAの設定"]。

.手順
. VMware Live Site Recovery マシンからキャッシュされた ONTAP tools のクレデンシャルを削除するには、次のコマンドを実行します：
+
.. `sudo su <enter root password>`
.. `docker ps`
.. `docker exec -it <container_id> sh`
.. `cd conf/`
.. `rm -rf *`


. Perlコマンドを実行して、SRAに新しいクレデンシャルを設定します。
+
.. `cd ..`
.. `perl command.pl -I --otv-ip <OTV_IP>:8443 --otv-username <OTV_ADMIN_USERNAME> --otv-password <OTV_ADMIN_PASSWORD> --vcenter-guid <VCENTER_GUID>` パスワードの値は一重引用符で囲む必要があります。
+
ストレージ認証情報が保存されたことを確認する成功メッセージが表示されます。SRAは、指定されたIPアドレス、ポート、および認証情報を使用してSRAサーバーと通信できます。







== 証明書の変更後にVMware Live Site RecoveryアプライアンスでvCenterを再構成する

vCenter証明書が変更された場合（たとえば、vCenterのアップグレード後）、Site Recovery拡張機能でサムプリントの不一致エラーが発生する可能性があります。この問題を解決するには、次の手順を実行します。

.手順
. VMware Live Site Recovery アプライアンスで vCenter を再構成
+
.. ブラウザでVMware Live Site Recoveryアプライアンスの管理インターフェイスを開きます： `\https://<SRM_IP>:5480`
.. * Summary * タブを選択します。
.. vCenter Server 接続の *Reconfigure* を選択します。
+
これにより、vCenterから最新の証明書のサムプリントが取得され、受け入れられます。



. サイトペアリングを再接続してください（エラーが続く場合）
+
再設定後も指紋不一致エラーが解消されない場合：

+
.. vCenterユーザーインターフェイスにログインします。
.. *Site Recovery* 拡張機能に移動します。
.. *Site Pairing* セクションを探してください。
.. *再接続*を選択して、更新された証明書でサイトペアリングを再確立します。



