---
permalink: protect/verify-the-replicated-storage-environment.html 
sidebar: sidebar 
keywords: SRA, storage replication adapter, storage discovery, SnapMirror, custom policy, array pairing, VMware Live Site Recovery 
summary: Storage Replication Adapter（SRA\）を設定したら、保護対象サイトとリカバリサイトが正常にペアリングされていることを確認する必要があります。レプリケートされたストレージシステムは、保護対象サイトとリカバリサイトの両方から検出可能である必要があります。 
---
= ONTAP toolsで複製されたストレージシステムを検証する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Storage Replication Adapter（SRA）を設定したら、保護対象サイトとリカバリサイトが正常にペアリングされていることを確認する必要があります。レプリケートされたストレージシステムは、保護対象サイトとリカバリサイトの両方から検出可能である必要があります。

.作業を開始する前に
* ストレージシステムを設定しておく必要があります。
* VMware Live Site Recoveryアレイマネージャを使用して、保護対象サイトとリカバリサイトをペアリングしておく必要があります。
* SRAのテストフェイルオーバー処理とフェイルオーバー処理を実行する前に、FlexCloneライセンスとSnapMirrorライセンスを有効にしておく必要があります。
* ソースサイトとデスティネーションサイトで同じSnapMirrorポリシーとスケジュールを使用する必要があります。
* カスタムスケジュールを設定したカスタムSnapMirrorポリシーを使用している場合は、保護サイトと復旧サイトの両方で同じスケジュールとポリシーを設定する必要があります。
* カスタムSnapMirrorポリシー（デフォルトまたはカスタムスケジュールのいずれか）を使用している場合は、新しいポリシーが認識されるように、ONTAP toolsからストレージ検出を実行する必要があります。これを行わないと、テストフェイルオーバーやフェイルオーバーを含むSRAワークフローが失敗します。次のポイントでストレージ検出を実行します：
+
** 復旧サイトでカスタムポリシーを作成した後。
** 保護対象サイトでポリシーを再作成する再保護処理の実行後。




.手順
. vCenter Server にログインします。
. *サイト回復* > *アレイ ベースのレプリケーション* に移動します。
. 必要なアレイペアを選択し、対応する詳細を確認します。
+
保護対象サイトとリカバリサイトで、ステータスが「有効」になっているストレージシステムが検出されている必要があります。


