---
permalink: concepts/key-points-about-assign-and-modify-permissions.html 
sidebar: sidebar 
keywords:  
summary: vCenter Server のアクセス許可を使用する際にはいくつかの点に注意する必要があります。VMware vSphere タスク用の ONTAP ツールを使用できるかどうかは、アクセス許可を割り当てた場所、およびアクセス許可の変更後にユーザが実行した操作によって決まります。 
---
= vCenter Serverの権限の割り当てと変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter Server のアクセス許可を使用する際にはいくつかの点に注意する必要があります。VMware vSphere タスク用の ONTAP ツールを使用できるかどうかは、アクセス許可を割り当てた場所、およびアクセス許可の変更後にユーザが実行した操作によって決まります。



== 権限を割り当てます

vCenter Server のアクセス許可は、 vSphere のオブジェクトおよびタスクへのアクセスを制限したい場合にのみ設定します。それ以外の場合は、管理者としてログインできます。このログインでは、すべての vSphere オブジェクトに自動的にアクセスできます。

権限の割り当て先によって、ユーザが実行できるONTAP tools for VMware vSphereタスクが決まります。

場合によっては、タスクを確実に完了させるために、ルートオブジェクトなどの上位レベルに権限を割り当てる必要があります。具体的には、特定の vSphere オブジェクトには適用されない権限（タスクの追跡など）がタスクに必要な場合や、必要な権限環境が vSphere 以外のオブジェクト（ストレージシステムなど）に必要な場合です。

このような場合は、子エンティティに継承されるようにアクセス許可を設定できます。子エンティティには、他の権限も割り当てることができます。子エンティティに割り当てたアクセス許可は、親エンティティから継承されたアクセス許可を上書きします。つまり、子エンティティにアクセス許可を付与して、ルートオブジェクトに割り当てられ、子エンティティに継承されるアクセス許可の範囲を制限できます。


TIP: 会社のセキュリティポリシーでアクセス許可を厳しく制限することが求められる場合を除き、ルートオブジェクト（ルートフォルダとも呼ばれる）にアクセス許可を割り当てることを推奨します。



== アクセス許可と非 vSphere オブジェクト

作成したアクセス許可はvSphere以外のオブジェクトに適用されます。たとえば、ストレージシステムは vSphere オブジェクトではありません。ストレージシステムの環境権限がある場合は、tools for VMware vSphereルートオブジェクトに割り当てることができるvSphereオブジェクトがないため、その権限を含むアクセス許可をONTAP tools for VMware vSphereルートオブジェクトに割り当てる必要があります。

たとえば、ONTAP tools for VMware vSphereの「Add/Modify/Skip storage systems」などの権限を含むすべてのアクセス許可は、ルートオブジェクトレベルに割り当てる必要があります。



== アクセス許可の変更

一度に変更できるアクセス許可は 1 つです。

アクセス許可に含まれる権限が変更された場合、そのアクセス許可が関連付けられたユーザは、更新されたアクセス許可を有効にするためにログアウトしてログインし直す必要があります。
