---
permalink: automation/overview-rest-apis.html 
sidebar: sidebar 
keywords: REST APIs, swagger 
summary: REST APIを使用してONTAP Tools for VMware vSphereの管理処理をいくつか実行する方法について説明します。REST API は Swagger Web ページから利用できます。 
---
= REST API の概要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
REST APIを使用して、VMware vSphereの管理処理用のONTAPツールをいくつか実行できます。REST API は Swagger Web ページから利用できます。

APIドキュメントを表示したり、呼び出しを手動で問題したりするには、_\https://loadbalancerIP:8443/_にあるSwagger Webページにアクセスします。


NOTE: すべてのAPIには、要求の本文と、swaggerページに記載されている例があります。このセクションに記載されているワークフローと例は、参照のみを目的としています。



== ONTAP tools for VMware vSphere REST APIにアクセスする方法

ONTAP REST API には、いくつかの方法でアクセスできます。



== ONTAP Tools for VMware vSphere APIオンラインドキュメントページ

Swaggerには、NetApp ONTAP tools for VMware vSphereプラグインのサポートページにあるハイパーリンクからアクセスできます。

最新バージョンの API のドキュメントページにアクセスするための URL の形式は次のとおりです。

'https://<loadbalancer_ip_address>/docs/api'



== カスタムのソフトウェアとツール

ONTAP Tools for VMware vSphere APIには、さまざまなプログラミング言語やツールを使用してアクセスできます。代表的なものとしては、 Python 、 Java 、 Curl 、 PowerShell などがあります。API を使用するプログラム、スクリプト、またはツールは、 REST Web サービスのクライアントとして機能します。プログラミング言語を使用すると、APIについての理解が深まり、ONTAP Tools for VMware vSphereの管理を自動化することができます。

最新バージョンの API に直接アクセスするためのベース URL の形式は次のとおりです。

'https：//<loadbalancer_ip_address>/api'

複数のバージョンがサポートされている場合に特定のバージョンの API にアクセスするには、次の形式の URL を使用します。

'https：//<loadbalancer_ip_address>/api/v1'



== Swagger UIからONTAP Tools for VMware vSphere APIのリファレンスドキュメントにアクセス

ONTAP REST APIのドキュメントには、ローカルのONTAPシステムのSwagger UIからアクセスできます。

* 始める前に *

次の情報が必要です。

* ONTAP クラスタ管理 LIF の IP アドレスまたはホスト名
* ONTAP REST APIにアクセスする権限を持つアカウントのユーザ名とパスワード


.手順
. ブラウザに URL を入力し、 *Enter* キーを押します。
_\ https：//<ip_address>/docs/api_
. ONTAPアカウントを使用してサインイン
+
ONTAP APIドキュメントページが表示され、主要なリソース別に分類されたAPI呼び出しが表示されます。
下部のカテゴリ。

. 個々の API 呼び出しの例として、 * cluster * カテゴリまでスクロールし、 * get/cluster * をクリックします。

