---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: ストレージバックエンドは、ESXiホストがデータストレージに使用するシステムです。 
---
= ストレージバックエンドを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージバックエンドを追加すると、ONTAPクラスタをオンボードできます。

* このタスクについて *

ONTAPクラスタにストレージバックエンドを追加する。vCenterが関連付けられたSVMのテナントとして機能するマルチテナンシーセットアップの場合は、ONTAP tools Managerを使用してクラスタを追加します。グローバルクラスタにストレージバックエンドを追加したら、クラスタを目的のvCenterテナントに関連付ける必要があります。vCenterテナントは、目的のStorage Virtual Machine（SVM）をオンボードする必要があります。これにより、SVMユーザはvVolデータストアをプロビジョニングできます。SVMを使用してvCenterにストレージを追加できます。

ローカルクラスタにストレージバックエンドを追加するには、vCenterサーバでONTAP toolsプラグインを使用します。

link:../concepts/ontap-tools-concepts-terms.html["主要な概念と用語"]このセクションで使用される用語の詳細については、を参照してください。

[role="tabbed-block"]
====
.ONTAP tools Managerの使用
--

NOTE: マルチテナントセットアップでは、SVMユーザクレデンシャルを使用するために、ストレージバックエンドクラスタをグローバルに、SVMをローカルに追加できます。

.手順
. WebブラウザからONTAP Tools Managerを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. サイドバーから* Storage backends *を選択します。
. ストレージバックエンドを追加し、サーバのIPアドレスまたはFQDN、ユーザ名、およびパスワードの詳細を指定します。
+

NOTE: IPv4とIPv6のアドレス管理LIFがサポートされます。



--
.vSphere Clientユーザインターフェイスを使用
--

NOTE: vSphere Clientユーザインターフェイスでストレージバックエンドを設定する場合、VVOLデータストアではSVMユーザを直接追加できない点に注意してください。

. vSphere Clientにログインします。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. サイドバーから* Storage backends *を選択します。
. ストレージバックエンドを追加し、サーバのIPアドレス、ユーザ名、パスワード、およびポートの詳細を指定します。
+

NOTE: SVMユーザを直接追加するには、クラスタベースのクレデンシャルとIPv4およびIPv6アドレス管理LIFを追加するか、SVM管理LIFにSVMベースのクレデンシャルを指定します。



.次の手順
リストが更新され、新しく追加されたストレージバックエンドがリストに表示されます。

--
====