---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: ストレージバックエンドは、ESXiホストがデータストレージに使用するシステムです。 
---
= ストレージバックエンドを追加します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージバックエンドは、ESXiホストがデータストレージに使用するシステムです。ストレージバックエンドは、ONTAP tools ManagerまたはvSphere Client UIを使用して追加できます。

* このタスクについて *

このタスクは、ONTAPクラスタをオンボードする際に役立ちます。ONTAP tools Managerを使用してストレージバックエンドを追加すると、ストレージバックエンドがグローバルクラスタに追加されます。グローバルクラスタをvCenter Serverインスタンスに関連付けて、SVMユーザにvVolデータストアのプロビジョニングを許可します。vCenterでストレージを追加するには、SVMを使用する必要があります。


NOTE: マルチテナントワークフローの場合は、ONTAP tools Managerを使用してONTAPクラスタをグローバルに追加し、必要なvCenterテナントにクラスタを関連付ける必要があります。その後、vCenterテナントで目的のStorage Virtual Machine（SVM）をオンボードする必要があります。マルチテナンシーが不要な場合は、vCenter UIのみを使用してONTAPシステムを直接追加してください。

[role="tabbed-block"]
====
.ONTAP tools Managerの使用
--

NOTE: ストレージバックエンドは、ONTAP tools ManagerまたはONTAP tools APIから追加するとグローバルになります。ストレージバックエンドは、vCenter Server APIから追加したときにローカルになります。たとえば、マルチテナントセットアップでは、SVMユーザクレデンシャルを使用するために、ストレージバックエンド（クラスタ）をグローバルに、SVMをローカルに追加できます。

* 手順 *

. WebブラウザからONTAP Tools Managerを起動します。 `\https://loadBalancerIP:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. サイドバーから* Storage backends *を選択します。
. 「 * 追加」を選択します。
. サーバのIPアドレスまたはFQDN、ユーザ名、パスワードを入力し、*[追加]*を選択します。
+

NOTE: IPv4とIPv6の管理LIFがサポートされます。管理LIFを使用するSVMユーザベースのクレデンシャルもサポートされます。



--
.vSphere Client UIノシヨウ
--

NOTE: vSphere Client UIを使用してストレージバックエンドを追加した場合、vVolデータストアでSVMユーザを直接追加することはできません。

. 次のコマンドを使用してvSphere Clientにログインします。 `\https://<vcenterip>/<ui>`
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. ONTAP toolsの左側のペインで、*[ストレージバックエンド]*に移動し、*[追加]*を選択します。
. [ストレージバックエンドの追加]*ウィンドウで、サーバのIPアドレス、ユーザ名、パスワード、およびポートの詳細を入力し、*[追加]*を選択します。
+

NOTE: クラスタベースのクレデンシャルとIPv4およびIPv6アドレス管理LIFを追加するか、SVMの管理LIFにSVMベースのクレデンシャルを指定して、SVMユーザを直接追加できます。



リストが更新され、新しく追加されたストレージバックエンドがリストに表示されます。

--
====