---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: ストレージバックエンドは、ESXiホストがデータストレージに使用するシステムです。 
---
= ONTAPツールにストレージバックエンドを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereを使用して、ESXi ホストのストレージ バックエンドを追加および管理します。クラスターまたは SVM をオンボードし、 MetroClusterサポートを有効にして、安全な接続のための証明書を検証できます。  ONTAPツール マネージャまたは vSphere クライアントを使用してストレージ バックエンドを構成し、証明書のステータスを監視し、クラスタの変更後にリソースを手動で再検出することができます。

ストレージ バックエンドをローカルに追加するには、 ONTAPツール インターフェイスでクラスタまたは SVM の認証情報を使用します。ローカル ストレージ バックエンドは、選択した vCenter Server でのみ使用できます。ONTAPツールは、 vVolsまたは VMFS データストアの管理のために SVM を vCenter Server にマッピングします。  VMFS データストアおよび SRA ワークフローの場合、クラスターをグローバルにマッピングせずに SVM 資格情報を使用できます。

グローバル ストレージ バックエンドを追加するには、 ONTAPツール マネージャーでONTAPクラスター認証情報を使用します。グローバル ストレージ バックエンドにより、vVol 管理に必要なクラスター リソースを識別する検出ワークフローが可能になります。マルチテナント環境では、SVM ユーザーをローカルに追加してvVolsデータストアを管理できます。

ONTAPでMetroClusterサポートが有効になっている場合は、ソース クラスターと宛先クラスターの両方をローカルまたはグローバル ストレージ バックエンドとしてオンボードします。

.作業を開始する前に
証明書に有効なサブジェクト別名 (SAN) フィールドが含まれていることを確認します。  ONTAPシステムは、SAN フィールドを使用してクラスタおよび SVM 管理 LIF を識別します。

[role="tabbed-block"]
====
.ONTAP tools Managerの使用
--

NOTE: マルチテナントセットアップでは、SVMユーザクレデンシャルを使用するために、ストレージバックエンドクラスタをグローバルに、SVMをローカルに追加できます。

.手順
. WebブラウザからONTAP Tools Managerを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. サイドバーから* Storage backends *を選択します。
. ストレージバックエンドを追加し、サーバのIPアドレスまたはFQDN、ユーザ名、およびパスワードの詳細を指定します。
+

NOTE: IPv4とIPv6のアドレス管理LIFがサポートされます。

. ONTAPクラスタ証明書を自動的に取得して承認するか、証明書の場所を参照して手動でアップロードします。
+

NOTE: 必要に応じて、メンテナンス コンソールからサブジェクト別名 (SAN) 検証を無効にすることができます。手順については、link:../manage/change-valid-flag.html["証明書検証フラグを変更する"] 。

. 追加するストレージ バックエンドがMetroCluster構成の一部である場合、 ONTAP Tools Manager はピア クラスタを追加するためのポップアップ メッセージが表示されます。  *追加*を選択し、 MetroClusterピア ストレージ バックエンドの詳細を入力します。
+

NOTE: ONTAPシステムがスイッチオーバーとスイッチバックを実行した後、 ONTAPツールの検出を手動で実行します。



--
.vSphere Clientユーザインターフェイスを使用
--

NOTE: vVolsデータストアは、vSphere クライアント ユーザー インターフェイスを介した SVM ユーザーの直接追加をサポートしていません。

. vSphere Clientにログインします。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. サイドバーから* Storage backends *を選択します。
. ストレージバックエンドを追加し、サーバのIPアドレス、ユーザ名、パスワード、およびポートの詳細を指定します。
+

NOTE: IPv4 または IPv6 管理 LIF でクラスターベースの認証情報を使用してストレージ バックエンドを追加できます。 SVM ユーザーを直接追加するには、SVM 管理 LIF とともに SVM ベースの認証情報を指定します。クラスターがすでにオンボードされている場合は、そのクラスターから SVM ユーザーを再度オンボードすることはできません。

. ONTAPクラスタ証明書を自動的に取得して承認するか、証明書の場所を参照して手動でアップロードします。
. 追加されたストレージ バックエンドがMetroCluster構成の一部である場合、 ONTAPツールは * MetroClusterピアの追加* 画面を表示します。ピア ストレージ バックエンドを追加するには、[*ピアの追加*] を選択します。
+

NOTE: ONTAPシステムがスイッチオーバーとスイッチバックを実行した後、 ONTAPツールの検出を手動で実行します。



.次の手順
ONTAPツールはリストを更新し、新しいストレージ バックエンドを表示します。

--
====
ONTAPツールは、*ストレージ バックエンド* ページに新しく追加されたストレージ バックエンドをリストします。証明書の有効期限が 30 日以内に切れる場合、 ONTAPツールは証明書の有効期限列に警告を表示します。有効期限が切れると、ストレージ システムに接続できなくなるため、 ONTAPツールはストレージ バックエンドを不明としてマークします。

.関連情報
https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_sw_config_configure_clusters.html["クラスタをMetroCluster構成に設定"]
