---
permalink: configure/add-vcenter.html 
sidebar: sidebar 
keywords:  
summary: vCenter ServerインスタンスをONTAP tools for VMware vSphereに追加して、vCenter Server環境内の仮想データストアを設定、管理、保護します。 
---
= ONTAPツールにvCenter Serverインスタンスを追加する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
vCenter ServerインスタンスをONTAP tools for VMware vSphereに追加して、vCenter Server環境内の仮想データストアを設定、管理、保護します。複数の vCenter Server インスタンスを追加する場合、ONTAP ツールと各 vCenter Server 間の安全な通信にはカスタム CA 証明書が必要です。

vCenter Server インスタンスを ONTAP tools Manager に登録する際は、vCenter Server 証明書に有効なサブジェクト代替名（SAN）拡張が含まれていることを確認してください。SAN 拡張には、DNS と IP アドレスの両方のエントリが含まれている必要があります。例：

[listing]
----
X509v3 extensions:
    X509v3 Subject Alternative Name:
        DNS: vcenter.example.com, DNS: vcenter, IP Address: 192.168.0.50
----
vCenter Server証明書にSAN拡張機能が含まれていない場合、またはSAN拡張機能に正しいDNSまたはIPアドレス値が含まれていない場合、証明書検証エラーが原因でONTAP tools操作が失敗する可能性があります。

.タスクの内容
ONTAPツールは vCenter Server と統合され、プロビジョニング、スナップショット、データ保護などのストレージ タスクを vSphere クライアントから直接実行します。

.手順
. Web ブラウザを開き、次の URL にアクセスします。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. vCenter Serverインスタンスをオンボードするには、* vCenters *>* Add *を選択します。vCenterのIPアドレスまたはホスト名、ユーザ名、パスワード、およびポートの詳細を入力します。
. 詳細オプションで、vCenter Server 証明書を自動的に取得 (承認) するか、手動でアップロードします。
+

NOTE: vCenterインスタンスをONTAP toolsに追加するために管理者アカウントは必要ありません。権限が制限された管理者アカウントなしでカスタムロールを作成できます。詳細については、を参照してください link:../concepts/rbac-vcenter-use.html["vCenter Server RBACとONTAP Tools for VMware vSphere 10の使用"] 。



vCenter ServerインスタンスをONTAP toolsに追加すると、次の処理が自動的にトリガーされます。

* ONTAPツールは、vCenter クライアント プラグインをリモート プラグインとして登録します。
* プラグインとAPIのカスタムPrivilegesがvCenter Serverインスタンスに適用されます。
* ユーザを管理するためのカスタムロールが作成されます。
* プラグインは、vSphereユーザインターフェイスにショートカットとして表示されます。

