---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereは、NetAppストレージシステムに最適なESXiホストのマルチパス設定とHBAタイムアウト設定を確認して設定します。 
---
= ONTAP toolsでESXiホストの設定を構成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ESXi サーバーのマルチパスとタイムアウト設定を構成すると、データの可用性と整合性を維持するのに役立ちます。プライマリ パスが使用できなくなった場合に、バックアップ ストレージ パスへの自動フェイルオーバーが可能になります。



== ESXiサーバのマルチパスとタイムアウトの設定

VMware vSphere 用の ONTAP ツールは、 ESXi ホストのマルチパス設定と HBA タイムアウト設定をチェックし、ネットアップストレージシステムに最も適した設定を行います。

.タスクの内容
設定とシステム負荷によっては、このプロセスに時間がかかる場合があります。  「最近のタスク」パネルで進行状況を確認できます。

.手順
. VMware vSphere Web Clientのホームページで、*[ホストおよびクラスタ]*を選択します。
. VMware vSphere Web Clientのショートカットページで、[plug-ins]セクションで* NetApp ONTAP tools *を選択します。
. ONTAP Tools for VMware vSphereプラグインの概要（ダッシュボード）にある* ESXiホストコンプライアンス*カードに移動します。
. [推奨設定の適用]*リンクを選択します。
. *推奨ホスト設定の適用* ウィンドウで、 NetApp推奨設定を使用するように更新するホストを選択し、*次へ* を選択します。
+

NOTE: ESXiホストを展開すると、現在の値を確認できます。

. 設定ページで、必要に応じて推奨値を選択します。
. 概要ペインで値を確認し、*[完了]*を選択します。進捗状況は、最近のタスクパネルで追跡できます。




== ESXiホストの値の設定

ONTAP tools for VMware vSphereを使用して、ESXi ホストのタイムアウトやその他の値を設定し、最適なパフォーマンスとフェイルオーバーを実現します。これらの値はNetAppテストに基づいて設定されます。

ESXi ホストでは、次の値を設定できます。



=== HBA / CNAアダプタ設定

次のパラメータをデフォルト値に設定します。

* Disk.QFullSampleSize
* Disk.QFullThreshold
* Emulex FC HBAタイムアウト
* QLogic FC HBAタイムアウト




=== MPIO設定

MPIO 設定は、 NetAppストレージ システムに最適なパスを選択します。  MPIO 設定では最適なパスを選択して使用します。

高パフォーマンス環境の場合、または単一の LUN データストアでテストする場合は、ラウンドロビン (VMW_PSP_RR) パス選択ポリシー (PSP) の負荷分散設定を調整してパフォーマンスを向上させます。デフォルトの IOPS 値を 1000 から 1 に設定します。


NOTE: MPIO 設定は、NVMe、NVMe/FC、NVMe/TCP プロトコルには適用されません。



=== NFS 設定

|===


| パラメータ | 設定する値 


| Net.TcpipHeapSize | 32だ 


| Net.TcpipHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128以上 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===