---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereは、NetAppストレージシステムに最適なESXiホストのマルチパス設定とHBAタイムアウト設定を確認して設定します。 
---
= ESXiサーバのマルチパスとタイムアウトの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 用の ONTAP ツールは、 ESXi ホストのマルチパス設定と HBA タイムアウト設定をチェックし、ネットアップストレージシステムに最も適した設定を行います。

* このタスクについて *

構成やシステムの負荷によっては、このプロセスに時間がかかることがあります。タスクの進行状況は、*[最近のタスク]*パネルに表示されます。タスクが完了すると、ホストステータスのアラートアイコンが通常のアイコンまたはリブート保留中のアイコンに変わります。

* 手順 *

. VMware vSphere Web Clientのホームページで、*[ホストおよびクラスタ]*をクリックします。
. ホストを右クリックし、* NetApp ONTAP tools *>* Update host data *を選択します。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *をクリックします。
. ONTAP Tools for VMware vSphereプラグインの概要（ダッシュボード）の* ESXiホストコンプライアンス*カードに移動します。
. [推奨設定の適用]*リンクを選択します。
. [推奨されるホスト設定を適用]*ウィンドウで、NetAppの推奨されるホスト設定に準拠するホストを選択し、*[次へ]*をクリックします。
+

NOTE: ESXiホストを展開すると、現在の値を確認できます。

. 設定ページで、必要に応じて推奨値を選択します。
. 概要ペインで値を確認し、*[完了]*をクリックします。進捗状況は、最近のタスクパネルで追跡できます。

