---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereは、NetAppストレージシステムに最適なESXiホストのマルチパス設定とHBAタイムアウト設定を確認して設定します。 
---
= ESXiサーバのマルチパスとタイムアウトの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ESXiサーバのマルチパスとタイムアウトを設定すると、プライマリパスに障害が発生した場合にバックアップストレージパスにシームレスに切り替えることができるため、高可用性とデータの整合性が確保されます。

VMware vSphere 用の ONTAP ツールは、 ESXi ホストのマルチパス設定と HBA タイムアウト設定をチェックし、ネットアップストレージシステムに最も適した設定を行います。

* このタスクについて *

構成とシステムの負荷によっては、このプロセスに時間がかかることがあります。タスクの進行状況は、[最近のタスク]パネルに表示されます。

* 手順 *

. VMware vSphere Web Clientのホームページで、*[ホストおよびクラスタ]*を選択します。
. ホストを右クリックし、* NetApp ONTAP tools *>* Update host data *を選択します。
. VMware vSphere Web Clientのショートカットページで、[plug-ins]セクションで* NetApp ONTAP tools *を選択します。
. ONTAP Tools for VMware vSphereプラグインの概要（ダッシュボード）にある* ESXiホストコンプライアンス*カードに移動します。
. [推奨設定の適用]*リンクを選択します。
. [推奨されるホスト設定を適用]*ウィンドウで、NetAppの推奨設定に準拠するように更新するホストを選択し、*[次へ]*を選択します。
+

NOTE: ESXiホストを展開すると、現在の値を確認できます。

. 設定ページで、必要に応じて推奨値を選択します。
. 概要ペインで値を確認し、*[完了]*を選択します。進捗状況は、最近のタスクパネルで追跡できます。

