---
permalink: configure/create-datastore.html 
sidebar: sidebar 
keywords:  
summary: ホスト クラスタ レベルでデータストアを作成すると、 ONTAPツールによってそれがすべての宛先ホストにマウントされ、必要な権限がある場合にのみアクションが有効になります。 
---
= ONTAP toolsでデータストアを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホスト クラスタ レベルでデータストアを作成すると、 ONTAPツールによってそれがすべての宛先ホストにマウントされ、必要な権限がある場合にのみアクションが有効になります。

*vCenter Server および ONTAP ツールで管理されるデータストアとネイティブ データストア間の相互運用性*

ONTAP tools for VMware vSphere以降、 ONTAPツールはデータストアにネストされた igroup を作成します。親 igroup はデータストアに固有のもので、子 igroup はホストにマップされます。 ONTAP System Manager からフラット igroup を作成し、それを使用してONTAPツールを使用せずに VMFS データストアを作成できます。参照 https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["SANイニシエータとigroupを管理する"]詳細についてはこちらをご覧ください。

ストレージをオンボードし、データストアの検出を実行すると、 ONTAPツールは VMFS データストア内のフラット igroup をネストされた igroup に変更します。以前のフラット igroup を使用して新しいデータストアを作成することはできません。ネストされた igroup を再利用するには、 ONTAPツール インターフェイスまたは REST API を使用します。

[role="tabbed-block"]
====
.vVolデータストアを作成する
--
ONTAP tools for VMware vSphere以降では、スペース効率の高い thin.vVol としてASA r2 システム上にvVolsデータストアを作成できます。  VASA プロバイダーは、vVol データストアを作成するときに、コンテナと必要なプロトコル エンドポイントを作成します。  VASA プロバイダーは、このコンテナーにバックアップ ボリュームを割り当てません。

.作業を開始する前に
* ルート アグリゲートが SVM にマップされていないことを確認します。
* 選択したvCenterにVASA Providerが登録されていることを確認してください。
* ASA r2 ストレージ システムでは、SVM を SVM ユーザーのアグリゲートにマッピングする必要があります。


.手順
. vSphere Clientにログインします。
. ホスト システム、ホスト クラスター、またはデータ センターを右クリックし、* NetApp ONTAPツール* > *データストアの作成* を選択します。
. [VVols]*[データストアタイプ]*を選択します。
. [Datastore name]*と[Protocol]*の情報を入力します。
+

NOTE: ASA R2システムでは、VVOLのiSCSIプロトコルとFCプロトコルがサポートされます。

. データストアを作成するStorage VMを選択します。
. 詳細オプション（advanced options）で：
+
** *カスタム エクスポート ポリシー* を選択した場合は、すべてのオブジェクトに対して vCenter で検出を実行するようにしてください。このオプションは使用しないことをお勧めします。
** iSCSIプロトコルとFCプロトコルには* Custom initiator group * nameを選択できます。
+

NOTE: ASA r2 ストレージ システム タイプ SVM では、データストアは論理コンテナにすぎないため、ストレージ ユニット (LUN/名前空間) は作成されません。



. [ストレージ属性]*ペインで、新しいボリュームを作成するか、既存のボリュームを使用できます。ただし、これら2種類のボリュームを組み合わせてVVOLデータストアを作成することはできません。
+
新しいボリュームを作成するときに、データストアで QoS を有効にできます。デフォルトでは、LUN 作成要求ごとに 1 つのボリュームが作成されます。  ASA r2 ストレージ システム上のvVolsデータストアの場合は、この手順をスキップします。

. [サマリ]*ペインで選択内容を確認し、*[完了]*を選択します。


--
.NFSデータストアを作成する
--
NFS データストアは、NFS プロトコルを使用して ESXi ホストを共有ストレージに接続します。これらはシンプルで柔軟性があり、VMware vSphere 環境で使用されます。

.手順
. vSphere Clientにログインします。
. ホスト システム、ホスト クラスター、またはデータ センターを右クリックし、* NetApp ONTAPツール* > *データストアの作成* を選択します。
. [データストアの種類]*フィールドで[NFS]を選択します。
. [名前とプロトコル]*ペインに、データストア名、サイズ、およびプロトコルの情報を入力します。詳細オプションで*[データストアクラスタ]*および*[Kerberos認証]*を選択します。
+

NOTE: Kerberos認証は、NFS 4.1プロトコルが選択されている場合にのみ使用できます。

. [ストレージ]ペインで*[プラットフォーム]*と*[Storage VM]*を選択します。
. 詳細オプションで *カスタム エクスポート ポリシー* を選択した場合は、vCenter ですべてのオブジェクトの検出を実行します。このオプションは使用しないことをお勧めします。
+

NOTE: SVM のデフォルトまたはルート ボリューム ポリシーを使用して NFS データストアを作成することはできません。

+
** アドバンストオプションの*[非対称]*トグルボタンは、プラットフォームのドロップダウンでパフォーマンスまたは容量が選択されている場合にのみ表示されます。
** プラットフォーム ドロップダウンで *Any* オプションを選択すると、vCenter 内のすべての SVM が表示されます。プラットフォームと非対称フラグは可視性に影響しません。


. [ストレージ属性]*ペインで、ボリューム作成用のアグリゲートを選択します。アドバンストオプションで、必要に応じて*[スペースリザベーション]*および*[QoSを有効にする]*を選択します。
. [概要]*ペインで選択内容を確認し、*[完了]*を選択します。


ONTAPツールは NFS データストアを作成し、それをすべてのホストにマウントします。

--
.VMFSデータストアの作成
--
VMFS は、仮想マシン ファイルを保存するためのクラスター化されたファイル システムです。  vMotion および高可用性機能のために、複数の ESXi ホストが同じ VM ファイルに同時にアクセスできます。

保護されているクラスタの場合：

* VMFS データストアのみを作成できます。保護されたクラスターに VMFS データストアを追加すると、自動的に保護されます。
* 保護されているホストクラスタが1つ以上あるデータセンターにデータストアを作成することはできません。
* 親ホスト クラスタが「自動フェイルオーバー デュプレックス ポリシー」(均一構成または非均一構成) によって保護されている場合、ESXi ホスト上にデータストアを作成することはできません。
* VMFSデータストアは、非同期関係で保護されているESXiホストにのみ作成できます。「自動フェイルオーバーデュプレックス」ポリシーで保護されているホストクラスタの一部であるESXiホストでは、データストアを作成してマウントすることはできません。


.作業を開始する前に
* ONTAPストレージ側で各プロトコルのサービスとLIFを有効にします。
* ASA R2ストレージシステムで、SVMユーザ用のアグリゲートにSVMをマッピングします。
* NVMe/TCPプロトコルを使用している場合はESXiホストを設定します。
+
.. を確認します。 https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=san&productid=49677&releases_filter=589,578,518,508,448&deviceCategory=san&details=1&partner=399&Protocols=1&transportTypes=3&isSVA=0&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc["VMware Compatibility Guide"]
+

NOTE: VMware vSphere 7.0 U3以降のバージョンでは、NVMe/TCPプロトコルがサポートされます。ただし、VMware vSphere 8.0以降のバージョンを推奨します。

.. ネットワーク インターフェイス カード (NIC) ベンダーが NVMe/TCP プロトコルを使用した ESXi NIC をサポートしているかどうかを確認します。
.. NIC ベンダーの仕様に従って、NVMe/TCP 用に ESXi NIC を設定します。
.. VMware vSphere 7リリースを使用している場合は、VMwareサイトの手順に従って https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/configure-adapters-for-nvme-over-tcp-storage/configure-vmkernel-binding-for-the-tcp-adapter.html["NVMe over TCPアダプタ用のVMkernelバインドの設定"]NVMe/TCPポートバインドを設定します。VMware vSphere 8リリースを使用している場合は、に従って https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-tcp-on-esxi.html["ESXiでのNVMe over TCPの設定"]NVMe/TCPポートバインドを設定します。
.. VMware vSphere 7リリースの場合は、ページの手順に従って https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-storage-7-0/about-vmware-nvme-storage/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["NVMe over RDMAまたはNVMe over TCPソフトウェアアダプタの有効化"]NVMe/TCPソフトウェアアダプタを設定します。VMware vSphere 8リリースの場合は、に従って https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/8-0/vsphere-storage-8-0/about-vmware-nvme-storage/configuring-nvme-over-rdma-roce-v2-on-esxi/add-software-nvme-over-rdma-or-nvme-over-tcp-adapters.html["ソフトウェアNVMe over RDMAまたはNVMe over TCPアダプタの追加"]NVMe/TCPソフトウェアアダプタを設定します。
.. link:../configure/discover-storage-systems-and-hosts.html["ストレージシステムとホストを検出"]ESXiホストでアクションを実行します。詳細については、を参照してください https://community.netapp.com/t5/Tech-ONTAP-Blogs/How-to-Configure-NVMe-TCP-with-vSphere-8-0-Update-1-and-ONTAP-9-13-1-for-VMFS/ba-p/445429["VMFSデータストア用にNVMe/TCPをvSphere 8.0 Update 1およびONTAP 9 VMFS.13.1で設定する方法"]。


* NVME/FC プロトコルを使用している場合は、次の手順を実行して ESXi ホストを構成します。
+
.. ESXiホストでNVMe over Fabrics（NVMe-oF）が有効になっていない場合は有効にします。
.. SCSIゾーニングを完了します。
.. ESXiホストとONTAPシステムが物理レイヤと論理レイヤで接続されていることを確認します。




ONTAP SVMをFCプロトコル用に設定する方法については、を参照してください https://docs.netapp.com/us-en/ontap/san-admin/configure-svm-fc-task.html["FC用のSVMの設定"]。

VMware vSphere 8.0でNVMe/FCプロトコルを使用する方法の詳細については、を参照してください https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["ONTAP を搭載したESXi 8.x向けのNVMe-oFホスト構成"]。

VMware vSphere 7.0でNVMe/FCを使用する方法の詳細については https://docs.netapp.com/us-en/ontap-sanhost/nvme_esxi_8.html["ONTAP NVMe/FC Host Configuration Guide"]、およびを参照して http://www.netapp.com/us/media/tr-4684.pdf["TR-4684"]ください。

.手順
. vSphere Clientにログインします。
. ホスト システム、ホスト クラスター、またはデータ センターを右クリックし、* NetApp ONTAPツール* > *データストアの作成* を選択します。
. VMFSデータストアタイプを選択します。
. *名前とプロトコル* ペインにデータストアの名前、サイズ、プロトコル情報を入力します。新しいデータストアを既存の VMFS クラスタに追加するには、[詳細オプション] でデータストア クラスタを選択します。
. [ストレージ]*ペインでStorage VMを選択します。必要に応じて、[アドバンストオプション]*セクションで*[カスタムイニシエータグループ名]*を指定します。データストア用に既存のigroupを選択するか、カスタム名を指定して新しいigroupを作成できます。
+
NVMe/FC または NVMe/TCP プロトコルを選択すると、新しい名前空間サブシステムが作成され、名前空間マッピングに使用されます。  ONTAPツールは、データストア名を含む自動生成された名前を使用してネームスペース サブシステムを作成します。  *ストレージ* ペインの詳細オプションの *カスタム名前空間サブシステム名* フィールドで、名前空間サブシステムの名前を変更できます。

. ストレージ属性*ペインで、次の手順を実行します。
+
.. ドロップダウンオプションから*[アグリゲート]*を選択します。
+

NOTE: ASA r2 ストレージ システムの場合、ストレージが分散されているため、*Aggregate* オプションは表示されません。ASAストレージシステムタイプのSVMを選択すると、ストレージ属性ページにQoSを有効にするためのオプションが表示されます。

.. ONTAPツールは、選択したプロトコルに基づいて、シン スペース リザーブを持つストレージ ユニット (LUN/名前空間) を作成します。
+

NOTE: ONTAP 9.16.1以降では、ASA R2ストレージシステムでクラスタあたり最大12ノードがサポートされます。

.. 異機種混在クラスタで12ノードのSVMを使用するASA R2ストレージシステムの場合は、[パフォーマンスサービスレベル]*を選択します。このオプションは、選択したSVMが同種クラスタの場合、またはSVMユーザを使用している場合は使用できません。
+
「any」は、パフォーマンスサービスレベル（PSL）のデフォルト値です。この設定では、ONTAPの分散配置アルゴリズムを使用してストレージユニットが作成されます。ただし、必要に応じて、パフォーマンスまたは極端なオプションを選択できます。

.. 必要に応じて*[既存のボリュームを使用する]*、*[QoSを有効にする]*オプションを選択し、詳細を指定します。
+

NOTE: ASA r2 ストレージ タイプでは、ボリュームの作成または選択はストレージ ユニットの作成 (LUN/名前空間) には適用されません。したがって、これらのオプションは表示されません。

+

NOTE: 既存のボリュームを使用して、NVMe/FC または NVMe/TCP プロトコルを使用した VMFS データストアを作成することはできません。  VMFS データストア用の新しいボリュームを作成します。



. [概要]*ペインでデータストアの詳細を確認し、*[終了]*を選択します。



NOTE: 保護対象のクラスタにデータストアを作成すると、「The datastore is being mounted on a protected Cluster」という読み取り専用メッセージが表示されます。

.結果
ONTAPツールは VMFS データストアを作成し、それをすべてのホストにマウントします。

--
====