---
permalink: configure/discover-storage-systems-and-hosts.html 
sidebar: sidebar 
keywords:  
summary: vSphere ClientでONTAP tools for VMware vSphereを初めて実行すると、ONTAP tools for VMware vSphereによって、ESXiホスト、そのLUNとNFSエクスポート、およびLUNとエクスポートを所有するNetAppストレージシステムが検出されます。 
---
= ONTAP toolsでストレージシステムとホストを検出する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereをvSphere Client で初めて起動すると、ESXi ホスト、それに関連付けられた LUN と NFS エクスポート、およびこれらのリソースを所有するNetAppストレージ システムが自動的に検出されます。

.作業を開始する前に
* すべての ESXi ホストの電源がオンになっていて接続されていることを確認します。
* 検出対象となるすべてのストレージ仮想マシン (SVM) が実行中であり、各クラスタ ノードに使用中のストレージ プロトコル (NFS または iSCSI) 用に構成されたデータ LIF が少なくとも 1 つあることを確認します。


.タスクの内容
新しいストレージ システムを検出したり、既存のストレージ システムを更新して、最新の容量とセットアップの詳細を取得できます。ストレージ システム アクセス用のONTAP tools for VMware vSphereを変更することもできます。

ストレージシステムを検出する際、ONTAP tools for VMware vSphereは、vCenter Serverインスタンスで管理しているESXiホストから情報を収集します。

.手順
. vSphere Clientの[ホーム]ページで、*[ホストおよびクラスタ]*を選択します。
. 必要なデータセンターを右クリックし、* NetApp ONTAPツール* > *ホスト データの更新* を選択します。
+
[*確認*（Confirm *）]ダイアログボックスで、選択内容を確認します。

. 検出されたストレージコントローラのうち、ステータスがのものを選択し `Authentication Failure`、*[操作]*>*[変更]*を選択します。
. [ストレージ・システムの変更]ダイアログ・ボックスに必要な情報を入力します
. が搭載されたすべてのストレージコントローラについて、手順4と5を繰り返します `Authentication Failure` ステータス。


検出プロセスが完了したら、次の操作を実行します。

* ONTAP tools for VMware vSphereを使用して、アダプタ設定、MPIO設定、またはNFS設定の列にアラートアイコンが表示されているホストのESXiホストを設定します。
* ストレージシステムのクレデンシャルを入力します。

