---
permalink: configure/esxi-host-values.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 用の ONTAP ツールを使用して ESXi ホストにタイムアウト値やその他の値を設定することで、最適なパフォーマンスが得られ、フェイルオーバーが正常に実行されるようにすることができます。ONTAP tools for VMware vSphereが設定する値は、社内のNetAppテストに基づいています。 
---
= ESXiホストの値の設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereを使用すると、ESXiホストでタイムアウトなどの値を設定して、最適なパフォーマンスが確保され、フェイルオーバーが正常に実行されるようにすることができます。ONTAP tools for VMware vSphereが設定する値は、社内のNetAppテストに基づいています。

ESXi ホストでは、次の値を設定できます。



== HBA / CNAアダプタ設定

NetAppストレージシステムに推奨されるHBAタイムアウト設定を設定します。

|===
| パラメータ | 設定する値 


| Disk.QFullSampleSize | すべての構成で32。この値を設定すると、I/Oエラーを回避できます。 


| Disk.QFullThreshold | 8（すべての構成）この値を設定すると、I/Oエラーを回避できます。 


| Emulex FC HBAタイムアウト | デフォルト値。 


| QLogic FC HBAタイムアウト | デフォルト値。 
|===


== MPIO設定

MPIO設定では、NetAppストレージシステムの優先パスを定義します。また、使用可能なパスのうちどのパスが最適化されているか（インターコネクトケーブルを経由する非最適化パスではなく）が判断され、そのいずれかのパスに優先パスが設定されます。

ハイパフォーマンス環境や、単一のLUNデータストアでパフォーマンスをテストする場合は、ラウンドロビン（VMW_PSP_RR）パス選択ポリシー（PSP）の負荷分散設定をデフォルトのIOPS設定である1000から1に変更することを検討してください。



== NFS 設定

|===


| パラメータ | 設定する値 


| Net.TcpipHeapSize | 32だ 


| Net.TcpipHeapMax | 1024 MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes | 256 


| NFS.MaxQueueDepth | 128以上 


| NFS.HeartbeatMaxFailures | 10 


| NFS.HeartbeatFrequency | 12 


| NFS.HeartbeatTimeout | 5 
|===