---
permalink: configure/install-nfs-vaai-plug-in.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereを使用して、NetApp NFS Plug-in for VMware vStorage APIs for Array Integration\（VAAI\）をインストールできます。 
---
= ONTAPツールを使用してNFS VAAIプラグインをインストールする
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS vStorage API for Array Integration (NFS VAAI) プラグインは、VMware vSphere を NFS ストレージ アレイに接続します。  ONTAP tools for VMware vSphereを使用してVAAIプラグインをインストールします。これにより、ESXiホストの代わりにNFSストレージアレイが特定のストレージ操作を処理できるようになります。

.作業を開始する前に
* インストールパッケージをダウンロードし https://mysupport.netapp.com/site/products/all/details/nfsplugin-vmware-vaai/downloads-tab["NetApp NFS Plug-in for VMware VAAI"]ます。
* ESXiホストとvSphere 7.0U3の最新のパッチ以降のバージョンとONTAP 9.14.1以降のバージョンがあることを確認します。
* NFSデータストアをマウント


.手順
. vSphere Clientにログインします。
. プラグインセクションで*ショートカット*>* NetApp ONTAP tools *を選択します。
. [設定]*>*[NFS VAAIツール]*を選択します。
. VAAI プラグインを vCenter Server にすでにアップロードしている場合は、*既存のバージョン*で*変更*を選択します。まだアップロードしていない場合は、[アップロード] を選択します。
. ファイルを参照して選択し `.vib`、*アップロード*を選択してファイルをONTAPツールにアップロードします。
. [ESXiホストにインストール]*を選択し、NFS VAAIプラグインをインストールするESXiホストを選択して、*[インストール]*を選択します。
+
vSphere Web Client には、プラグインをインストールできる ESXi ホストのみが表示されます。インストールの進行状況は「最近のタスク」セクションで確認できます。

. インストール後にESXiホストを手動で再起動します。
+
ESXi ホストを再起動すると、 ONTAP tools for VMware vSphereNFS VAAI プラグインが自動的に検出され、有効になります。



.次の手順
NFS VAAI プラグインをインストールし、ESXi ホストを再起動した後、VAAI コピー オフロードの NFS エクスポート ポリシーを構成します。エクスポート ポリシー ルールが次の要件を満たしていることを確認します。

* 関連するONTAPボリュームは NFSv4 呼び出しを許可します。
* ルート ユーザーはルートのままとなり、すべてのジャンクション親ボリュームで NFSv4 が許可されます。
* VAAI サポートのオプションは、関連する NFS サーバーで設定されます。


詳細については、 https://kb.netapp.com/on-prem/ontap/DM/VAAI/VAAI-KBs/Configure_the_correct_NFS_export_policies_for_VAAI_copy_offload["VAAIコピーオフロードの正しいNFSエクスポートポリシーを設定する"] KB 記事。

.関連情報
https://docs.netapp.com/us-en/ontap/nfs-admin/support-vmware-vstorage-over-nfs-concept.html["VMware vStorage over NFSのサポート"]

https://docs.netapp.com/us-en/ontap/nfs-admin/enable-disable-nfsv40-task.html["NFSv4.0を有効または無効にする"]

https://docs.netapp.com/us-en/ontap/nfs-admin/ontap-support-nfsv42-concept.html#nfs-v4-2-security-labels["NFSv4 4.2 の ONTAP サポート"]
