---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: ONTAP Tools for VMware vSphereは、ホストクラスタの保護を管理します。 
---
= ONTAP toolsでホストクラスタを保護する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereは、ホストクラスタの保護を管理します。選択したSVMに属し、クラスタの1つ以上のホストにマウントされているすべてのデータストアが、ホストクラスタで保護されます。

.作業を開始する前に
ホスト クラスターを保護する前に、次の要件を満たしていることを確認してください。

* ホスト クラスタには、単一の SVM のデータストアのみが含まれます。
* ホスト クラスター上のデータストアは、クラスター外部のホストにはマウントされません。
* ホスト クラスタにマウントされるデータストアは、iSCSI または FC プロトコルを使用した VMFS データストアです。  NVMe/FC および NVMe/TCP プロトコルでは、 vVols、NFS、または VMFS データストアは使用できません。
* ホストにマウントされたFlexVol/LUN ボリュームに基づくデータストアは、どの整合性グループにも属しません。
* ホストにマウントされたFlexVol/LUN ボリュームに基づくデータストアは、 SnapMirror関係の一部ではありません。
* ホスト クラスターには少なくとも 1 つのデータストアが含まれています。


.手順
. vSphere Clientにログインします。
. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。
. 保護クラスタウィンドウでは、データストアの種類とソース ストレージ仮想マシン (VM) の詳細がシステムによって自動的に入力されます。保護されたデータストアを表示するには、データストア リンクを選択します。
. [関係の追加]*を選択します。
. [ SnapMirror関係の追加]*ウィンドウで、*[ターゲットStorage VM]*と*[ポリシー]*タイプを選択します。
+
ポリシータイプはAsynchronousまたはAutomatedFailOverDuplexのいずれかです。

+
SnapMirror関係をAutomatedFailOverDuplexタイプのポリシーとして追加する場合は、ONTAP tools for VMware vSphereが導入されているvCenterに、ストレージバックエンドとしてターゲットStorage VMを追加する必要があります。

+
AutomatedFailOverDuplex ポリシー タイプには、均一なホスト構成と非均一なホスト構成があります。 *均一ホスト構成*トグル ボタンを選択すると、ホスト イニシエーター グループ構成がターゲット サイトに暗黙的に複製されます。詳細については、 link:../concepts/ontap-tools-concepts-terms.html["主要な概念と用語"] 。

. 不均一なホスト構成を選択した場合は、そのクラスタ内の各ホストのホストアクセス（ソース/ターゲット）を選択します。
. 「 * 追加」を選択します。
. *ホスト クラスター保護の変更* 操作を使用して、ホスト クラスター保護を編集できます。省略記号メニュー オプションを使用して、関係を編集または削除できます。
. [保護]*ボタンを選択します。
+
システムはジョブ ID の詳細を含む vCenter タスクを作成し、最近のタスク パネルにその進行状況を表示します。これは非同期タスクです。ユーザー インターフェイスにはリクエストの送信ステータスのみが表示され、タスクが完了するまで待機しません。

. 保護されたホスト クラスターを表示するには、* NetApp ONTAPツール* > *保護* > *ホスト クラスター リレーションシップ* に移動します。整合性グループを選択すると、その容量、関連付けられているデータストア、および子整合性グループが表示されます。


[NOTE]
====
作成後 1 時間以内に保護を解除する必要がある場合は、まずストレージの検出を実行してください。

====
.関連情報
https://www.vmware.com/docs/vmware-vsphere-metro-storage-cluster-vmsc["VMware vSphere メトロ ストレージ クラスタ (vMSC)"^]
