---
permalink: configure/registration-process.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereを使用して、VASA プロバイダーを vCenter Server インスタンスに登録できます。 
---
= ONTAPツールを使用して VASA プロバイダを vCenter Server インスタンスに登録する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereを使用して、VASA プロバイダーを vCenter Server インスタンスに登録します。これにより、ストレージ ポリシー ベースの管理、 vVolsサポート、 ONTAPシステム上の VMware Live Site Recovery アプライアンスとの統合が可能になります。

VASA プロバイダ設定には、選択した vCenter Server の登録ステータスが表示されます。

.手順
. vSphere Clientにログインします。
. プラグインセクションで*ショートカット*>* NetApp ONTAP tools *を選択します。
. *設定* > *VASA プロバイダー設定*を選択します。  ONTAPツールでは、VASA プロバイダの登録ステータスが未登録として表示されます。
. [登録]*ボタンを選択してVASA Providerを登録します。
. VASA プロバイダーの名前と資格情報を入力します。ユーザー名には文字、数字、アンダースコアのみを含めることができます。パスワードの長さを 8 文字から 256 文字の間で設定します。
. [*Register] を選択します。
. 登録が正常に完了し、ページが更新されると、 ONTAPツールには登録済みの VASA プロバイダーのステータス、名前、バージョンが表示されます。


.次の手順
vCenterクライアントからオンボードしたVASA Providerが[VASA Provider]の下に表示されていることを確認します。

.手順
. vCenter Server インスタンスに移動します。
. 管理者のクレデンシャルでログインします。
. [ストレージプロバイダ]*>*[設定]*を選択します。オンボードしたVASA Providerが正しく表示されていることを確認します。

