---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.5, ONTAP tools for VMware vSphere' 
summary: ONTAP tools for VMware vSphereで利用できる新しい機能について説明します。 
---
= ONTAP tools for VMware vSphereの新機能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereで利用できる新しい機能について説明します。

* *プラットフォームの資格*


ONTAP tools for VMware vSphereは、 ASA r2 システムのサポートを追加し、最新のハードウェアおよびソフトウェア構成との互換性を提供します。このリリースにはONTAP 9.16.1 および 9.17.1 との統合も含まれており、サポートされる環境が拡張されています。

* *VMware の資格と認定資格*


ONTAP tools for VMware vSphereは、現在の VMware 相互運用性認定標準に準拠しており、ESXi ホストと vCenter Server の両方をサポートしています。

* * MetroClusterサポート*


このリリースでは、 MetroCluster (MCC) 構成のサポートが導入され、高可用性と災害復旧機能が強化されています。

* *セキュリティと証明書管理*


このリリースでは、自己署名証明書の管理が合理化され、ユーザー エクスペリエンスとセキュリティ標準への準拠が強化されます。  ONTAP tools for VMware vSphereのONTAPおよび ONTAP ツールを保護するための、改善された証明書検証ワークフローを提供します。

* *レプリケーションの強化*


このリリースでは、 ASA r2 システムの SRA およびSnapMirror Active Sync を含む階層的整合性グループを使用した VMFS レプリケーションがサポートされます。ゼロ RPO バックアップをサポートし、データ保護とリカバリを改善します。

* *アップグレードと移行*


以前のバージョンのONTAP tools for VMware vSphereからONTAP tools for VMware vSphere 10.5 へのアップグレードおよび移行プロセスは、シームレスかつ効率的に実行され、ダウンタイムを最小限に抑え、スムーズな移行を保証するように設計されています。



== サポートされているONTAPプラットフォームと vCenter Server バージョン

バージョン互換性に関する最新情報については、 https://imt.netapp.com/matrix/imt.jsp?components=105475;&solution=1777&isHWU&src=IMT["NetApp Interoperability Matrix Tool"^] 。
