---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereの単一インスタンスで、複数のvCenter Serverインスタンスを管理できます。ONTAP Tools for VMware vSphereは、VASA Provider用の自己署名証明書を使用して導入されます。これにより、vVolデータストアに対して管理できるvCenter Serverインスタンスは1つだけです。 
---
= 証明書を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereの単一インスタンスで、複数のvCenter Serverインスタンスを管理できます。

カスタムのCA証明書が必須であるvCenterが複数ある環境では、証明書の発行先のドメイン名が仮想IPアドレスにマッピングされていることを確認します。ドメイン名に対して_nslookup_checkが実行され、ドメインが目的のIPアドレスに解決されているかどうかが確認されます。証明書は、ロードバランサのIPアドレスのドメイン名とIPアドレスを使用して作成する必要があります。


NOTE: カスタムCAに自己署名をアップグレードする場合、異なるドメインにマッピングされた別のロードバランサIPアドレスはサポートされません。

[role="tabbed-block"]
====
.ONTAP Tools証明書
--
ONTAP toolsタブには、証明書の種類（自己署名/ CA署名）やドメイン名などの詳細が表示されます。導入時にデフォルトで自己署名証明書が生成されます。証明書を更新するか、証明書をCAにアップグレードできます。

* 手順 *

. WebブラウザからONTAP Tools Managerを起動します。 `\https://loadBalanceIP:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. 証明書を更新するには、*証明書*>* ONTAP tools *>*更新*オプションを選択します。
+

NOTE: 証明書の有効期限が切れている場合や有効期限に近づいている場合は、証明書を更新できます。証明書が更新され、ユーザインターフェイスからログアウトされるまで、システムはオフラインになります。

+
*Renew*は、証明書タイプがCA署名済みの場合に使用できる唯一のオプションです。CA署名証明書の場合は、サーバ証明書、秘密鍵、ルートCA、および中間証明書の詳細を指定できるダイアログボックスが表示されます。

. 自己署名証明書をカスタムCA証明書にアップグレードするには、*[証明書]*>*[ ONTAP tools ]*>*[CAにアップグレード]*オプションを選択します。
+
.. [証明書をカスタムCA *にアップグレード]ポップアップで、サーバ証明書、サーバ証明書の秘密鍵、ルートCA証明書、および中間証明書のファイルをアップロードします。ツールヒントには証明書の概要が表示されます。
.. この証明書を生成したドメイン名を入力します。
.. [* アップグレード ] をクリックします。
+

NOTE: アップグレードが完了するまでシステムはオフラインになり、ユーザインターフェイスからログアウトされます。CA署名証明書から自己署名証明書に切り替えることはできません。





--
.VASAプロバイダ証明書
--
ONTAP Tools for VMware vSphereは、VASA Provider用の自己署名証明書を使用して導入されます。これにより、vVolデータストアに対して管理できるvCenter Serverインスタンスは1つだけです。複数のvCenter Serverインスタンスを管理していて、複数のvCenter ServerインスタンスでVVol機能を有効にする場合は、ONTAP tools Managerインターフェイスを使用して自己署名証明書をカスタムCA証明書に変更する必要があります。

* 手順 *

. WebブラウザからONTAP Tools Managerを起動します。 `\https://loadBalanceIP:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. 証明書を更新するには、*[証明書]*>*[VASA Provider]*または* ONTAP tools *>*[更新]*オプションを選択します。
. 自己署名証明書をカスタムCA証明書にアップグレードするには、*[証明書]*>*[VASA Provider]*または* ONTAP tools *>*[CAにアップグレード]*オプションを選択します。
+
.. [証明書をカスタムCA *にアップグレード]ポップアップで、サーバ証明書、サーバ証明書の秘密鍵、ルートCA証明書、および中間証明書のファイルをアップロードします。ツールヒントには証明書の概要が表示されます。
.. この証明書を生成したドメイン名を入力します。
.. [* アップグレード ] をクリックします。
+

NOTE: アップグレードが完了するまでシステムはオフラインになり、ユーザインターフェイスからログアウトされます。CA署名証明書から自己署名証明書に切り替えることはできません。





--
====