---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: ONTAP tools for VMware vSphereの単一インスタンスで、複数のvCenter Serverインスタンスを管理できます。ONTAP Tools for VMware vSphereは、VASA Provider用の自己署名証明書を使用して導入されます。これにより、vVolデータストアに対して管理できるvCenter Serverインスタンスは1つだけです。 
---
= 証明書を管理します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
導入時に、 ONTAPツールおよび VASA プロバイダー用の自己署名証明書がデフォルトで生成されます。ONTAPツール マネージャ インターフェイスを使用して、証明書を更新したり、カスタム CA にアップグレードしたりできます。マルチ vCenter 展開ではカスタム CA 証明書を使用する必要があります。

.作業を開始する前に
始める前に、次のものを用意する必要があります。

* 仮想 IP アドレスにマッピングされたドメイン名。
* ドメイン名の nslookup が成功し、正しい IP アドレスに解決されることが確認されました。
* ドメイン名とONTAPツールの IP アドレスを使用して作成された証明書。



NOTE: ONTAP toolsのIPアドレスは、Fully Qualified Domain Name（FQDN；完全修飾ドメイン名）にマッピングする必要があります。証明書には、サブジェクト名またはサブジェクト名のONTAP toolsのIPアドレスにマッピングされた同じFQDNが含まれている必要があります。


NOTE: CA署名証明書から自己署名証明書に切り替えることはできません。

[role="tabbed-block"]
====
.ONTAP tools証明書のアップグレード
--
ONTAP toolsタブには、証明書の種類（自己署名/ CA署名）やドメイン名などの詳細が表示されます。導入時にデフォルトで自己署名証明書が生成されます。証明書を更新するか、証明書をCAにアップグレードできます。

.手順
. WebブラウザからONTAP Tools Managerを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. 証明書を更新するには、*証明書*>* ONTAP tools *>*更新*を選択します。
+
証明書の有効期限が切れている場合や有効期限が近づいている場合は、証明書を更新できます。更新オプションは、証明書タイプがCA署名の場合に使用できます。ポップアップウィンドウで、サーバ証明書、秘密鍵、ルートCA、および中間証明書の詳細を指定します。

+

NOTE: 証明書が更新されるまでシステムはオフラインになり、ONTAP tools Managerインターフェイスからログアウトされます。

. 自己署名証明書をカスタムCA証明書にアップグレードするには、*[証明書]*>*[ ONTAP tools ]*>*[CAにアップグレード]*オプションを選択します。
+
.. ポップアップウィンドウで、サーバ証明書、サーバ証明書の秘密鍵、ルートCA証明書、および中間証明書のファイルをアップロードします。
.. この証明書を生成したドメイン名を入力し、証明書をアップグレードします。
+

NOTE: アップグレードが完了するまでシステムはオフラインになり、ONTAP tools Managerインターフェイスからログアウトされます。





--
.VASA Providerの証明書のアップグレード
--
ONTAP Tools for VMware vSphereは、VASA Provider用の自己署名証明書を使用して導入されます。これにより、vVolデータストアに対して管理できるvCenter Serverインスタンスは1つだけです。複数のvCenter Serverインスタンスを管理している環境でVVol機能を有効にする場合は、自己署名証明書をカスタムのCA証明書に変更する必要があります。

.手順
. WebブラウザからONTAP Tools Managerを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. 証明書を更新するには、*[証明書]*>*[VASA Provider]*または* ONTAP tools *>*[更新]*を選択します。
. 自己署名証明書をカスタムCA証明書にアップグレードするには、*[証明書]*>*[VASA Provider]*または* ONTAP tools *>*[CAへのアップグレード]*を選択します。
+
.. ポップアップウィンドウで、サーバ証明書、サーバ証明書の秘密鍵、ルートCA証明書、および中間証明書のファイルをアップロードします。
.. この証明書を生成したドメイン名を入力し、証明書をアップグレードします。
+

NOTE: アップグレードが完了するまでシステムはオフラインになり、ONTAP tools Managerインターフェイスからログアウトされます。





--
====