---
permalink: manage/delete-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: ホストクラスタの保護を解除すると、データストアの保護は解除されます。 
---
= ONTAP toolsでホストクラスタ保護を削除する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ホストクラスタの保護を解除すると、データストアの保護は解除されます。

.手順
. 保護されたホスト クラスターのリストを表示するには、* NetApp ONTAPツール* > *保護* > *ホスト クラスター リレーションシップ* に移動します。
+
このページでは、保護されたホスト クラスター、保護状態、 SnapMirror関係、およびステータスを監視します。整合性グループを選択して、容量、関連付けられたデータストア、および子グループを表示します。

. *ホスト クラスター保護* ウィンドウで、クラスターの横にある省略記号メニューを選択し、*保護の削除* を選択します。
+
** SnapMirror非同期関係のみを持つホスト クラスタから保護を削除する場合は、ストレージ要素を手動で削除する必要があります。ストレージ要素には、コンシステンシー グループ、ボリューム ( ONTAPシステムの場合)、ストレージ ユニット (LUN)、スナップショットが含まれます。
** 自動フェイルオーバーのデュプレックスベースのSnapMirrorポリシー関係と非階層型コンシステンシ グループのみを持つホスト クラスタから保護を削除する場合は、セカンダリ ストレージ上の関連するストレージ要素を同じ画面から直接削除できます。
** SnapMirrorポリシーとバックアップの階層型整合性グループの両方を持つホスト クラスタから保護を削除すると、バックアップへの影響に関する警告が表示されます。確認して続行します。確認後、セカンダリ ストレージ上の関連するストレージ要素を削除します。クリーンアップを行わない場合、ストレージ要素はセカンダリ サイトに残ります。



