---
permalink: manage/delete-ds.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Delete datastore action：データストアを削除します。NFSまたはVMFSデータストアの場合は、ダイアログボックスに、そのデータストアを使用しているVMのリストが表示されます。 
---
= データストアの削除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このセクションでは、vCenter Server のONTAPツールを使用して NFS、VMFS、またはvVolsデータストアを削除する方法について説明します。

データストアを削除すると、データストアの種類に応じて次のアクションが実行されます。

* vVol コンテナがマウント解除されました。
* igroup が使用されていない場合は、iqn は igroup から削除されます。
* vVol コンテナが削除されます。
* フレックス ボリュームはストレージ アレイ上に残ります。


選択したデータストアにvVolsが存在しない場合にのみ、データストアを削除できます。

.手順
. vSphere Clientにログインします。
. ホスト システム、ホスト クラスター、またはデータ センターを右クリックし、* NetApp ONTAPツール* > *データストアの削除* を選択します。
+

NOTE: 仮想マシンによって使用されるデータストアを削除することはできません。削除する前に仮想マシンを別のデータストアに移動します。ボリュームが保護されたホスト クラスターの一部である場合は、ボリュームを削除できません。

+
.. NFS または VMFS データストアの場合、データストアを使用している VM のリストを含むダイアログ ボックスが表示されます。
.. VMFS データストアに仮想マシンが関連付けられていない場合は、確認ダイアログが表示されます。ホスト クラスター保護が有効になっていて、AFD 関係が存在する場合は、セカンダリ ストレージ要素をクリーンアップできます。
.. ASA r2 システム上の保護された VMFS データストアの場合は、削除する前に保護が解除されていることを確認してください。 ONTAP 9.17.1 およびONTAP tools for VMware vSphere以降では、保護されたデータストアを削除できます。保護グループ内の唯一のデータストアである場合、ホスト クラスタ保護は自動的に削除されます。
.. vVolsデータストアの場合、 vVolsが存在しない場合にのみデータストアを削除できます。  *データストアの削除* ダイアログ ボックスには、 ONTAPクラスターからボリュームを削除するオプションが含まれています。
.. ASA r2 システム上のvVolsデータストアの場合、*データストアの削除* オプションを使用してONTAPからバックアップ ボリュームを削除することはできません。


. ONTAPストレージの元のボリュームを削除するには、* ONTAPクラスタのボリュームを削除する*を選択します。
+

NOTE: 保護されたホスト クラスタの一部である統合ONTAPストレージ上の VMFS データストアの場合、 ONTAPクラスタからボリュームを削除することはできません。



NFS、VMFS、またはvVolsデータストアを削除しても、親 igroup はONTAPシステムに残ります。どの LUN にもマップされていない子 igroup は自動的に削除されます。 ONTAPツールは毎日クリーンアップを実行し、マップされていないデフォルトの親 igroup を削除します。カスタム親 igroup は、 ONTAPで手動で削除する必要があります。残っている親 igroup は古くなり、 ONTAPツールで再利用できなくなります。
