---
permalink: manage/edit-appliance-settings.html 
sidebar: sidebar 
keywords:  
summary: 管理者パスワードは、ONTAP tools Managerを使用して変更できます。 
---
= アプライアンス設定の編集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools Managerを使用して、ノードサイズのスケールアップ、サービスの管理、ONTAP tools for VMware vSphereのハイアベイラビリティ（HA）セットアップへのアップグレードを行います。

ONTAP toolsアプライアンスは、最初はシングルノード非HA構成で導入されます。設定は、*[Edit appliance settings]*ウィンドウで編集できます。

* 始める前に *

指定したOVAテンプレートのバージョンが最初のノードと同じであることを確認します。

* 手順 *

. WebブラウザからONTAP Tools Managerを起動します。 `\https://loadBalanceIP:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. 概要セクションの*アプライアンス設定の編集*をクリックします。
. [サービス]セクションでは、要件に応じて、VASA Provider、vVol構成のインポート、ディザスタリカバリ（SRA）などのオプションのサービスを有効にすることができます。
+
サービスを初めて有効にするときは、VASA Provider / SRAクレデンシャルを作成する必要があります。これは、vCenter ServerでVASA Provider / SRAサービスを登録または有効にするために使用します。

+

NOTE: オプションのサービスを無効にするには、ONTAP toolsで管理しているvCenter Serverがこれらのサービスを使用していないことを確認してください。

+
*[VVol構成のインポートを許可する]*オプションは、VASA Providerサービスが有効になっている場合にのみ表示されます。このオプションを使用すると、ONTAP tools 9.xからONTAP tools 10.3にvVolデータを移行できます。

. [構成]セクションでは、ONTAP toolsの各ノードサイズをスケールアップし、要件に応じてHA構成を有効にすることができます。変更を行うには、vCenter Serverのクレデンシャルが必要です。
+
ONTAP toolsがHA構成の場合は、コンテンツライブラリの詳細を変更できます。新しい編集を送信するには、パスワードをもう一度入力する必要があります。

+

NOTE: スケールアップできるのは、ONTAP toolsのノードサイズのみです。ノードを現在のサイズから小さいサイズにスケールダウンすることはできません。非HAの場合、サポートされる最大構成はmediumです。HA構成では、中規模および大規模の構成がサポートされます。

. HAの切り替えボタンを使用して、HA構成を有効にします。HA構成を選択すると、HA関連の入力用に追加の* HA設定*ページが表示されます。
+
** コンテンツライブラリは、ONTAP toolsノードVMが実行されているvCenter Serverに属している必要があります。vCenter Serverのクレデンシャルを使用して、アプライアンスの変更用のOVAテンプレートを検証およびダウンロードします。
** HA導入を有効にするには、ONTAPツールをホストしている仮想マシンをESXiホストに直接導入しないでください。代わりに、クラスタまたはリソースプールに導入する必要があります。
** 有効にすると、HA構成から非HAシングルノード構成にリバートできなくなります。


. アプライアンス設定の編集*ウィンドウの* HA設定*セクションで、ノード2とノード3の詳細を入力できます。OVAの一部として導入されるONTAP toolsのデフォルトノードはノード1です。ONTAP tools for VMware vSphereでは、HAセットアップで3つのノードがサポートされます。
+

NOTE: ワークフローを容易にするため、ほとんどの入力オプションにはノード1のネットワークの詳細があらかじめ入力されています。ただし、ウィザードの最終ページに移動する前に、入力データを編集できます。最初のノードでIPv6アドレスが有効になっている場合にのみ、他の2つのノードのIPv6の詳細を入力できます。

+
ESXiホストにONTAP tools VMが1つだけ含まれていることを確認します。入力は、次のウィンドウに移動するたびに検証されます。

. [Summary]*セクションで詳細を確認し、*[Save]*をクリックして変更を適用します。


[Overview]*ページには、導入のステータスが表示されます。また、ジョブIDを使用して、[Jobs]ビューからアプライアンス設定の編集ジョブステータスを追跡することもできます。

HAの導入に失敗して新しいノードのステータスが[New]になっている場合は、vCenterで新しいVMを削除してから、HAの有効化処理を再試行してください。

左側パネルの*[アラート]*タブには、ONTAP tools for VMware vSphereのアラートが表示されます。
