---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 保護対象ホストクラスタのSnapMirror関係を編集することができます。関係を追加、変更、および削除できます。ただし、整合グループ名は編集できません。 
---
= 保護されているホストクラスタを変更
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
単一のワークフローでホスト クラスターの保護設定を変更できます。次の変更がサポートされています。

* 保護対象のクラスタに新しいデータストアまたはホストを追加します。
* 新しいSnapMirror関係を保護設定に追加します。
* 保護設定から既存のSnapMirror関係を削除します。
* 既存のSnapMirror関係を変更します。



NOTE: ホスト クラスターの保護を作成、編集、または削除した後、変更を反映するにはストレージ検出を実行する必要があります。ストレージ検出を実行しない場合、定期的なストレージ検出がトリガーされた後に変更が反映されます。



== ホストクラスタ保護の監視

保護された各ホスト クラスタの保護ステータス、 SnapMirror関係、データストア、およびSnapMirrorステータスを監視します。

.手順
. vSphere Clientにログインします。
. * NetApp ONTAPツール* > *保護* > *ホスト クラスター リレーションシップ* に移動します。
+
保護列には、保護の状態を示すアイコンが表示されます。

. アイコンにカーソルを合わせると、詳細が表示されます。




== 新しいデータストアまたはホストの追加

vCenter ユーザー インターフェイスを使用して、保護されたクラスターにホストを追加するか、データストアを作成します。

.手順
. vSphere Clientにログインします。
. 保護されたクラスタのプロパティを編集するには、次のいずれかを実行します。
+
.. * NetApp ONTAPツール* > *保護* > *ホストクラスタ関係*に移動し、クラスタの横にある省略記号メニューを選択して*編集*を選択するか、
.. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。


. vCenter ユーザー インターフェイスでデータストアを作成すると、保護されていないものとして表示されます。ダイアログ ボックスで、クラスター内のすべてのデータストアとその保護ステータスを表示できます。保護を有効にするには、[保護] ボタンを選択します。
+

NOTE: vCenter Server ユーザー インターフェイスでデータストアを作成した後、概要ページで *検出* を選択して、そのデータストアをホスト クラスタ内の保護の候補として表示します。次回の定期的な保護検出後に、保護ステータスが保護済みに更新されます。

. 新しい ESXi ホストを追加すると、保護ステータスは部分的に保護されていると表示されます。  SnapMirror設定の下の省略記号メニューを選択し、[編集] を選択して、新しく追加された ESXi ホストの近接性を設定します。
+

NOTE: 非同期関係の場合、第 3 サイトのターゲット SVM を同じインスタンスに追加できないため、 ONTAPツールでは編集がサポートされません。関係の設定を変更するには、System Manager またはターゲット SVM の CLI を使用します。

. 変更を加えたら、[保存] を選択します。
. 変更は*[クラスタの保護]*ウィンドウで確認できます。


ONTAPツールは vCenter タスクを作成し、*最近のタスク* パネルでその進行状況を追跡できます。



== 新しいSnapMirror関係を追加する

.手順
. vSphere Clientにログインします。
. 保護されたクラスタのプロパティを編集するには、次のいずれかを実行します。
+
.. * NetApp ONTAPツール* > *保護* > *ホストクラスタ関係*に移動し、クラスタの省略記号メニューを選択して*編集*を選択するか、
.. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。


. [関係の追加]*を選択します。
. ポリシータイプ「* Asynchronous *」または「* AutomatedFailOverDuplex *」として新しい関係を追加します。
. [保護]*を選択します。
+
変更は*[クラスタの保護]*ウィンドウで確認できます。



ONTAPツールは vCenter タスクを作成し、*最近のタスク* パネルでその進行状況を追跡できます。



== 既存のSnapMirror関係を削除する

SnapMirror非同期関係を削除するには、セカンダリ サイトの SVM またはクラスタがONTAP tools for VMware vSphereでストレージ バックエンドとして追加されていることを確認します。すべてのSnapMirror関係を一度に削除することはできません。関係を削除すると、対応する関係もONTAPクラスタから削除されます。自動フェイルオーバー デュプレックスSnapMirror関係を削除すると、システムは宛先データストアをマップ解除し、宛先ONTAPクラスタからコンシステンシ グループ、LUN、ボリューム、および igroup を削除します。

関係を削除すると、システムはセカンダリ サイトを再スキャンし、マップされていない LUN をホストからのアクティブ パスとして削除します。

.手順
. vSphere Clientにログインします。
. 保護されたクラスタのプロパティを編集するには、次のいずれかを実行します。
+
.. * NetApp ONTAPツール* > *保護* > *ホストクラスタ関係*に移動し、クラスタの省略記号メニューを選択して*編集*を選択するか、
.. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。


. SnapMirror設定の下にある省略記号メニューを選択し、*削除*を選択します。
+
** 保護されたホスト クラスターの非同期ポリシー タイプ ベースの関係を削除する場合は、3 次ストレージ クラスターからストレージ要素を手動で削除する必要があります。ストレージ要素には、コンシステンシ グループ、ボリューム ( ONTAPシステムの場合)、ストレージ ユニット (LUN/名前空間)、スナップショットが含まれます。
** 保護されたホスト クラスターの自動フェイルオーバー デュプレックス (AFD) ポリシーベースの関係を削除する場合は、セカンダリ ストレージ上の関連付けられているストレージ要素をインターフェイスから直接削除することを選択できます。
** 自動フェイルオーバー デュプレックス (AFD) ポリシーベースの関係を削除し、整合性グループがアプリケーション レベルのバックアップ用に階層化されている場合は、バックアップの影響に関する警告が表示されます。確認して続行します。確認後、セカンダリ ストレージ上の関連するストレージ要素を削除します。削除しない場合はセカンダリ サイトに残ります。




ONTAPツールは vCenter タスクを作成し、*最近のタスク* パネルでその進行状況を追跡できます。



== 既存のSnapMirror関係を変更する

SnapMirror の非同期関係を変更するには、セカンダリ サイトの SVM またはクラスタがONTAP tools for VMware vSphereでストレージ バックエンドとして追加されていることを確認します。自動フェイルオーバー デュプレックスSnapMirror関係では、均一構成のホスト近接性または非均一構成のホスト アクセスを更新できます。非同期と自動フェールオーバーのデュプレックス ポリシー タイプ間の変更はサポートされていません。クラスター内で新しく検出されたホストの近接性またはアクセス設定を構成できます。


NOTE: 既存のSnapMirror非同期関係を編集することはできません。

.手順
. vSphere Clientにログインします。
. 保護されたクラスタのプロパティを編集するには、次のいずれかを実行します。
+
.. * NetApp ONTAPツール* > *保護* > *ホストクラスタ関係*に移動し、クラスタの省略記号メニューを選択して*編集*を選択するか、
.. ホスト クラスターを右クリックし、* NetApp ONTAPツール* > *クラスターの保護* を選択します。


. AutomatedFailOverDuplex ポリシー タイプを選択した場合は、ホストの近接性またはホスト アクセスの詳細を追加します。
. [保護]*ボタンを選択します。


ONTAPツールは vCenter タスクを作成します。  *最近のタスク*パネルで進行状況を追跡します。
