---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: データセンター内の既存の仮想マシンを移行する際には、いくつかの留意事項を理解しておく必要があります。 
---
= ONTAP toolsにおける仮想マシンの移行とクローン作成に関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP tools for VMware vSphereは、コンピューティング専用（vMotion）、ストレージ専用（Storage vMotion）、およびすべてのデータストアにわたるコンピューティングとストレージの統合移行など、すべての主要な仮想マシン移行タイプをサポートしています。このトピックでは、基盤となるデータストアのタイプに関わらず、仮想マシンの移行とクローン作成を成功させるための重要な考慮事項とベストプラクティスについて概説します。



== 保護された仮想マシンを移行します

保護された仮想マシンは、以下の場所に移行できます：

* 別の ESXi ホスト上の同じデータストア
* 同じESXiホスト上の別の互換性のあるデータストア
* 別のESXiホスト上の別の互換性のあるデータストア


仮想マシンを別のFlexVolボリュームに移行すると、システムはそのボリュームのメタデータファイルを仮想マシン情報で更新します。仮想マシンが別のESXiホストに移行されても、ストレージが同じ場合、基盤となるFlexVolボリュームメタデータファイルは変更されません。

仮想マシンの移行に関する情報については、Broadcomのドキュメントを参照してください： https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vcenter-and-host-management/migrating-virtual-machines-host-management.html["vSphere仮想マシンの移行"]



== 保護された仮想マシンのクローン作成

保護された仮想マシンは、次の場所にクローニングできます。

* レプリケーション グループを使用した同じ FlexVol ボリュームの同じコンテナ
+
同じFlexVol volumeのメタデータファイルは、クローンされた仮想マシンの詳細情報で更新されます。

* レプリケーショングループを使用した異なるFlexVolボリュームの同じコンテナ
+
クローンされた仮想マシンが配置されているFlexVol volumeでは、メタデータファイルがクローンされた仮想マシンの詳細情報で更新されます。

* 別のコンテナまたはvVolsデータストア
+
クローンされた仮想マシンが配置されているFlexVolボリュームでは、メタデータファイルが仮想マシンの詳細情報で更新されます。



VMwareは現在、VMテンプレートにクローンされた仮想マシンをサポートしていません。

保護された仮想マシンのクローンのクローンがサポートされています。

詳細については、Broadcomのドキュメントを参照してください。 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["クローニング用仮想マシンの作成"]



== 仮想マシンのスナップショット

ONTAP tools は、標準的な VMware ワークフローを通じて仮想マシンのスナップショットをサポートします。スナップショットは、テストやパッチの準備などのユースケースを想定した、短期的なロールバック ポイントです。これらは、バックアップやレプリケーションベースのデータ保護の代替手段ではありません。スナップショット上で仮想マシンを長期間実行すると、不安定性やデータ損失を引き起こす可能性があります。

サポートされているすべてのデータストアタイプで「crash consistent state（障害など予期しないシャットダウン時と同様）」の状態のスナップショット（メモリ状態を含まないスナップショット。仮想マシンを一貫性のある状態に再起動するために使用できます）を取得できます。VMware Toolsを使用してメモリ内のデータをディスクに書き出してからキャプチャする、静止スナップショットもサポートされています。スナップショットの種類と動作の概要については、 https://knowledge.broadcom.com/external/article/342618/overview-of-virtual-machine-snapshots-in.html["vSphereにおける仮想マシンのスナップショットの概要"]を参照してください。


NOTE: メモリのスナップショットは、実行中のメモリの状態をキャプチャし、仮想マシンを一時的に停止させます。ONTAP tools のワークフローではサポートされていません。仮想マシンにメモリ スナップショットがある場合は、ONTAP tools で管理される整合性グループまたはホスト クラスタ関係に仮想マシンを含める前に、メモリ スナップショットを削除する必要があります。

ASA r2ストレージシステムでは、仮想マシンのスナップショットの動作が他のストレージタイプとは異なります。スナップショットは読み取り専用です。仮想マシンを起動すると、VASA Providerは読み取り専用のスナップショットからLUNを作成し、IOPSを有効にします。仮想マシンの電源を切ると、VASA ProviderはLUNを削除し、IOPSを無効にします。

仮想マシンのスナップショットの管理方法については、Broadcomのドキュメント https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/vsphere-virtual-machine-administration/managing-virtual-machinesvsphere-vm-admin/using-snapshots-to-manage-virtual-machinesvsphere-vm-admin.html["スナップショットを使用して仮想マシンを管理する"]を参照してください。
