---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: データセンター内の既存の仮想マシンを移行する際の考慮事項について理解しておく必要があります。 
---
= 仮想マシンの移行またはクローニングに関する考慮事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データセンター内の既存の仮想マシンを移行する際には、いくつかの考慮事項を理解しておく必要があります。



== 保護された仮想マシンを移行します

保護された仮想マシンは次の場所に移行できます。

* 別の ESXi ホストにある同じ VVOL データストア
* 同じ ESXi ホスト上に互換性のある異なる VVOL データストアがあります
* 互換性がある異なる VVOL データストアが別の ESXi ホストにあります


仮想マシンを別のFlexVol volumeに移行すると、システムはそのボリュームのメタデータ ファイルを仮想マシン情報で更新します。仮想マシンが同じストレージ内の別の ESXi ホストに移行された場合、基盤となるFlexVol volumeメタデータ ファイルは変更されません。



== 保護された仮想マシンのクローン作成

保護された仮想マシンは、次の場所にクローニングできます。

* レプリケーショングループを使用して同じ FlexVol ボリュームの同じコンテナ
+
同じ FlexVol ボリュームのメタデータファイルが、クローニングされた仮想マシンの詳細で更新されます。

* レプリケーショングループを使用して、異なる FlexVol の同じコンテナ
+
クローニングされた仮想マシンが配置された FlexVol ボリュームでは、クローニングされた仮想マシンの詳細がメタデータファイルに反映されます。

* 別のコンテナまたは vVol データストアです
+
クローニングされた仮想マシンが配置された FlexVol ボリュームでは、メタデータファイルに仮想マシンの詳細が更新されます。



VMware は現在、VM テンプレートにクローンされた仮想マシンをサポートしていません。

保護された仮想マシンのクローン作成がサポートされています。

詳細については、を参照してください https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/7-0/vsphere-virtual-machine-administration-guide-7-0/deploying-virtual-machinesvm-admin/clone-an-existing-virtual-machine-h5vm-admin.html["クローニング用仮想マシンの作成"]。



== 仮想マシンのスナップショット

現在、メモリのない仮想マシンのスナップショットのみがサポートされています。仮想マシンにメモリ付きの Snapshot がある場合、その仮想マシンは保護対象とはみなされません。

また、メモリ スナップショットを持つ保護されていない仮想マシンを保護することもできません。このリリースでは、仮想マシンの保護を有効にする前にメモリ スナップショットを削除する必要があります。

ASA r2 ストレージ タイプを持つ Windows VM の場合、仮想マシンのスナップショットは読み取り専用です。  VM の電源をオンにすると、VASA プロバイダーは読み取り専用スナップショットから LUN を作成し、IOPS を有効にします。  VM の電源をオフにすると、VASA プロバイダーは LUN を削除し、IOPS を無効にします。
