---
permalink: manage/mount-datastores-on-host.html 
sidebar: sidebar 
keywords:  
summary: データストアをマウントすると、他のホストからストレージにアクセスできるようになります。ホストを VMware 環境に追加したあとで、そのホストにデータストアをマウントできます。 
---
= NFSデータストアとVMFSデータストアのマウント
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
データストアをマウントすると、他のホストからストレージにアクセスできるようになります。ホストを VMware 環境に追加したあとで、そのホストにデータストアをマウントできます。


NOTE: 新しいESXiホストを追加する場合、 https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-0/use-quickstart-to-add---host-to-a-cluster.html["vSphere クラスタに ESX ホストを追加するワークフロー"]スケジュールされたホスト検出が完了するまで待機してから、 ONTAPツールに表示されます。あるいは、 NetApp ONTAPツールの概要画面から手動で検出を実行することもできます。

.タスクの内容
* vSphere Clientのバージョンと選択したデータストアのタイプによっては、一部の右クリック操作が無効または使用できない場合があります。
+
** vSphere Client 8.0以降のバージョンを使用している場合、一部の右クリックオプションは非表示になります。
** vSphere 7.0U3からvSphere 8.0のバージョンでは、オプションが表示されていても、この操作は無効になります。


* ホスト クラスタが均一な構成で保護されている場合、vSphere はマウント データストア オプションを無効にします。


.手順
. vSphere Clientの[ホーム]ページで、*[ホストおよびクラスタ]*を選択します。
. 左側のナビゲーションペインで、ホストを含むデータセンターを選択します。
. NFS/VMFS データストアをホストまたはホスト クラスターにマウントするには、右クリックして * NetApp ONTAPツール* > * データストアのマウント* を選択します。
. マウントするデータストアを選択し、*[マウント]*を選択します。


.次の手順
進捗状況は、最近のタスクパネルで追跡できます。

.関連トピック
link:../manage/add-vsphere-host.html["新しい VMware vSphere ホストを追加する"]
