---
permalink: manage/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: Delete datastore action：データストアを削除します。NFSまたはVMFSデータストアの場合は、ダイアログボックスに、そのデータストアを使用しているVMのリストが表示されます。 
---
= ホストクラスタの保護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/
:firstname: [.lead]
:author: [.lead]
:authorinitials: [
:authors: [.lead]
:revdate: ONTAP tools for VMware vSphere manages protection of a host cluster.


選択したSVMに属する（クラスタの1つ以上のホストにマウントされている）すべてのデータストアが、ホストクラスタの下で（SMAの場合）保護されます。

.前提条件
ホストクラスタを保護する前に、次の条件を満たしていることを確認してください。ホストクラスタには、1つのSVMのデータストアのみがあります。SVM（SB）のバージョンが9.15.1よりもあとである必要があります。ホストクラスタにマウントされたデータストアは、クラスタ外のホストにはマウントしないでください。です。ホストクラスタにマウントされたすべてのデータストアがVMFSデータストアである必要があります。です。ホストクラスタにマウントされたデータストアを形成しているFlexVolまたはLUNが、既存のCGに含まれていないことを確認してください。です。FlexVolまたはLUNをSnapMirror関係に含めることはできません。

.手順
. 次のコマンドを使用してvSphere Clientにログインします。 `\https://vcenterip/ui`
. ホストクラスタを右クリックし、* NetApp ONTAP tools *>*[クラスタの保護]*を選択します。
. [クラスタの保護]ウィンドウで、保護するデータストアの保護設定を入力します。ホストクラスタには、1つのSVM（クラスタ）のデータストアのみを含めることができます。
. いずれかのターゲットONTAPクラスタと[Storage VM]オプションを選択します。
. データストアの元のボリュームにローカルSnapshotポリシーを適用する場合は、*[ローカルSnapshotを有効にする]*チェックボックスを選択します。
. 選択したAutomatedFailoverDuplexポリシー、ターゲットクラスタ、およびターゲットStorage VMでデータストアを保護する場合は、の*[Enable SnapMirror]*チェックボックスをオンにし、*[Add Relationship]*をオンにします。
. 均一な構成の場合は、*[ホスト構成の均一化]*トグルボタンをtrueに選択します。
. 統一されたホスト構成トグルボタンの選択に応じて、各ホストに* Host Proximity *または* Access *を提供します。
. 「 * 追加」を選択します。
. 概要ページを確認し、[Protect]を選択します。


タスクがvCenter上に作成されます。生成されたジョブIDを使用してタスクを監視します。
