---
permalink: manage/storage-backend.html 
sidebar: sidebar 
keywords:  
summary: ストレージバックエンドは、ESXiホストがデータストレージに使用するシステムです。 
---
= ストレージバックエンドを管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ストレージバックエンドは、ESXiホストがデータストレージに使用するシステムです。



== ストレージの検出

スケジュールされた検出によってストレージの詳細がすぐに更新されるのを待たずに、ストレージ バックエンドの検出をオンデマンドで実行できます。  MetroCluster構成の場合、スイッチオーバー後にONTAPツールの検出を手動で実行します。

ストレージバックエンドを検出するには、次の手順を実行します。

.手順
. vSphere Clientにログインします。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. ONTAPツールの左側のペインで、*ストレージ バックエンド* に移動し、ストレージ バックエンドを選択します。
. 縦の省略記号メニューを選択し、*ストレージの検出*を選択します。


進捗状況は、[最近のタスク]パネルで追跡できます。



== ストレージバックエンドの変更

ストレージ バックエンドの資格情報またはポート名を変更できます。 ONTAPツール マネージャを使用して、グローバルONTAPクラスタのストレージ バックエンドを変更することもできます。証明書の有効期限が 30 日以内に切れる場合、 ONTAPツールは警告を表示します。ストレージ バックエンドを変更し、 ONTAP管理者からの新しい証明書をアップロードします。

ストレージ バックエンドを変更すると、 ONTAP tools for VMware vSphereはストレージ バックエンドの検出を実行し、ストレージの詳細を更新します。

ストレージバックエンドを変更するには、このセクションの手順を実行します。

. vSphere Clientにログインします。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. ONTAPツールの左側のペインで、*ストレージ バックエンド* に移動し、ストレージ バックエンドを選択します。
. クレデンシャルまたはポート名を変更するには、縦の省略記号メニューを選択し、*[変更]*を選択します。進捗状況は、[最近のタスク]パネルで追跡できます。


次のように、 ONTAPツール マネージャーを使用してグローバルONTAPクラスターを変更します。

. WebブラウザからONTAP Tools Managerを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. サイドバーからストレージバックエンドを選択します。
. 変更するストレージバックエンドを選択します。
. 垂直楕円メニューを選択し、*修正*を選択します。
. クレデンシャルまたはポートを変更できます。ストレージバックエンドを変更するには、*[Username]*と*[Password]*を入力します。




== ストレージバックエンドの削除

ストレージ バックエンドを削除する前に、ストレージ バックエンドに接続されているすべてのデータストアを削除する必要があります。ストレージ バックエンドを削除するには、以下の手順に従います。

. vSphere Clientにログインします。
. ショートカットページで、プラグインセクションの* NetApp ONTAP tools *を選択します。
. ONTAPツールの左側のペインで、*ストレージ バックエンド* に移動し、ストレージ バックエンドを選択します。
. 縦の省略記号メニューを選択し、[削除] を選択します。ストレージ バックエンドにデータストアが含まれていないことを確認します。最近のタスク パネルで進行状況を追跡できます。


ONTAP tools Managerを使用して、グローバルONTAPクラスタの削除処理を実行できます。

. WebブラウザからONTAP Tools Managerを起動します。 `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 導入時に指定したONTAP tools for VMware vSphere管理者のクレデンシャルを使用してログインします。
. サイドバーから* Storage backends *を選択します。
. 削除するストレージバックエンドを選択してください
. 垂直の楕円メニューを選択し、*削除*を選択します。




== ストレージバックエンドのドリルダウンビュー

ストレージ バックエンド ページには、すべてのストレージ バックエンドが一覧表示されます。追加したストレージ バックエンドに対してストレージの検出、変更、および削除の操作を実行できますが、クラスタの下の個々の子 SVM に対しては実行できません。

コンポーネントの概要を表示するには、親クラスターまたは子クラスターを選択します。親クラスターの場合、アクション ドロップダウンを使用してストレージを検出し、ストレージ バックエンドを変更または削除します。

概要ページには、次の詳細が表示されます。

* ストレージバックエンドのステータス
* 容量情報
* VMに関する基本情報
* 証明書のステータスや有効期限などの証明書の詳細。
* ネットワークの IP アドレスやポートなどのネットワーク情報。子 SVM の場合、情報は親ストレージ バックエンドと同じです。
* ストレージ バックエンドに対して許可および制限されるPrivileges。子 SVM の場合、情報は親ストレージ バックエンドと同じです。  ONTAPツールは、クラスタベースのストレージ バックエンドでのみ権限を表示します。  SVM をストレージ バックエンドとして追加した場合、権限情報は表示されません。
* SVM またはクラスターの分解プロパティが「true」に設定されている場合、 ASA r2 システム クラスターのドリルダウン ビューにはローカル層タブが含まれません。
* ASA R2 SVMシステムでは、容量ポートレットは表示されません。容量ポータルは、SVMまたはクラスタに対してDisaggregatedプロパティが「true」に設定されている場合にのみ必要です。
* ASA R2 SVMシステムの場合は、[基本情報]セクションにプラットフォームタイプが表示されます。


[Interface]タブには、インターフェイスに関する詳細情報が表示されます。

[ローカル階層]タブには、アグリゲートリストに関する詳細情報が表示されます。
